Class {
	#name : 'S3SDL_PixelFormat',
	#superclass : 'S3Enumeration',
	#classVars : [
		'SDL_PIXELFORMAT_ABGR128_FLOAT',
		'SDL_PIXELFORMAT_ABGR1555',
		'SDL_PIXELFORMAT_ABGR2101010',
		'SDL_PIXELFORMAT_ABGR32',
		'SDL_PIXELFORMAT_ABGR4444',
		'SDL_PIXELFORMAT_ABGR64',
		'SDL_PIXELFORMAT_ABGR64_FLOAT',
		'SDL_PIXELFORMAT_ABGR8888',
		'SDL_PIXELFORMAT_ARGB128_FLOAT',
		'SDL_PIXELFORMAT_ARGB1555',
		'SDL_PIXELFORMAT_ARGB2101010',
		'SDL_PIXELFORMAT_ARGB32',
		'SDL_PIXELFORMAT_ARGB4444',
		'SDL_PIXELFORMAT_ARGB64',
		'SDL_PIXELFORMAT_ARGB64_FLOAT',
		'SDL_PIXELFORMAT_ARGB8888',
		'SDL_PIXELFORMAT_BGR24',
		'SDL_PIXELFORMAT_BGR48',
		'SDL_PIXELFORMAT_BGR48_FLOAT',
		'SDL_PIXELFORMAT_BGR565',
		'SDL_PIXELFORMAT_BGR96_FLOAT',
		'SDL_PIXELFORMAT_BGRA128_FLOAT',
		'SDL_PIXELFORMAT_BGRA32',
		'SDL_PIXELFORMAT_BGRA4444',
		'SDL_PIXELFORMAT_BGRA5551',
		'SDL_PIXELFORMAT_BGRA64',
		'SDL_PIXELFORMAT_BGRA64_FLOAT',
		'SDL_PIXELFORMAT_BGRA8888',
		'SDL_PIXELFORMAT_BGRX32',
		'SDL_PIXELFORMAT_BGRX8888',
		'SDL_PIXELFORMAT_EXTERNAL_OES',
		'SDL_PIXELFORMAT_INDEX1LSB',
		'SDL_PIXELFORMAT_INDEX1MSB',
		'SDL_PIXELFORMAT_INDEX2LSB',
		'SDL_PIXELFORMAT_INDEX2MSB',
		'SDL_PIXELFORMAT_INDEX4LSB',
		'SDL_PIXELFORMAT_INDEX4MSB',
		'SDL_PIXELFORMAT_INDEX8',
		'SDL_PIXELFORMAT_IYUV',
		'SDL_PIXELFORMAT_MJPG',
		'SDL_PIXELFORMAT_NV12',
		'SDL_PIXELFORMAT_NV21',
		'SDL_PIXELFORMAT_P010',
		'SDL_PIXELFORMAT_RGB24',
		'SDL_PIXELFORMAT_RGB332',
		'SDL_PIXELFORMAT_RGB48',
		'SDL_PIXELFORMAT_RGB48_FLOAT',
		'SDL_PIXELFORMAT_RGB565',
		'SDL_PIXELFORMAT_RGB96_FLOAT',
		'SDL_PIXELFORMAT_RGBA128_FLOAT',
		'SDL_PIXELFORMAT_RGBA32',
		'SDL_PIXELFORMAT_RGBA4444',
		'SDL_PIXELFORMAT_RGBA5551',
		'SDL_PIXELFORMAT_RGBA64',
		'SDL_PIXELFORMAT_RGBA64_FLOAT',
		'SDL_PIXELFORMAT_RGBA8888',
		'SDL_PIXELFORMAT_RGBX32',
		'SDL_PIXELFORMAT_RGBX8888',
		'SDL_PIXELFORMAT_UNKNOWN',
		'SDL_PIXELFORMAT_UYVY',
		'SDL_PIXELFORMAT_XBGR1555',
		'SDL_PIXELFORMAT_XBGR2101010',
		'SDL_PIXELFORMAT_XBGR32',
		'SDL_PIXELFORMAT_XBGR4444',
		'SDL_PIXELFORMAT_XBGR8888',
		'SDL_PIXELFORMAT_XRGB1555',
		'SDL_PIXELFORMAT_XRGB2101010',
		'SDL_PIXELFORMAT_XRGB32',
		'SDL_PIXELFORMAT_XRGB4444',
		'SDL_PIXELFORMAT_XRGB8888',
		'SDL_PIXELFORMAT_YUY2',
		'SDL_PIXELFORMAT_YV12',
		'SDL_PIXELFORMAT_YVYU'
	],
	#category : 'SDL3-Base',
	#package : 'SDL3',
	#tag : 'Base'
}

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> abgr128Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ABGR128_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> abgr1555 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ABGR1555
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> abgr2101010 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ABGR2101010
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> abgr32 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ABGR32
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> abgr4444 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ABGR4444
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> abgr64 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ABGR64
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> abgr64Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ABGR64_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> abgr8888 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ABGR8888
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> argb128Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ARGB128_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> argb1555 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ARGB1555
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> argb2101010 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ARGB2101010
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> argb32 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ARGB32
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> argb4444 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ARGB4444
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> argb64 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ARGB64
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> argb64Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ARGB64_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> argb8888 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_ARGB8888
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgr24 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGR24
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgr48 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGR48
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgr48Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGR48_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgr565 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGR565
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgr96Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGR96_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgra128Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRA128_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgra32 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRA32
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgra4444 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRA4444
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgra5551 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRA5551
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgra64 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRA64
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgra64Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRA64_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgra8888 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRA8888
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgrx32 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRX32
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> bgrx8888 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_BGRX8888
]

{ #category : 'enum declaration' }
S3SDL_PixelFormat class >> enumDecl [

	^ #(
	SDL_PIXELFORMAT_UNKNOWN 0
	SDL_PIXELFORMAT_INDEX1LSB 286261504
	SDL_PIXELFORMAT_INDEX1MSB 287310080
	SDL_PIXELFORMAT_INDEX2LSB 470811136
	SDL_PIXELFORMAT_INDEX2MSB 471859712
	SDL_PIXELFORMAT_INDEX4LSB 303039488
	SDL_PIXELFORMAT_INDEX4MSB 304088064
	SDL_PIXELFORMAT_INDEX8 318769153
	SDL_PIXELFORMAT_RGB332 336660481
	SDL_PIXELFORMAT_XRGB4444 353504258
	SDL_PIXELFORMAT_XBGR4444 357698562
	SDL_PIXELFORMAT_XRGB1555 353570562
	SDL_PIXELFORMAT_XBGR1555 357764866
	SDL_PIXELFORMAT_ARGB4444 355602434
	SDL_PIXELFORMAT_RGBA4444 356651010
	SDL_PIXELFORMAT_ABGR4444 359796738
	SDL_PIXELFORMAT_BGRA4444 360845314
	SDL_PIXELFORMAT_ARGB1555 355667970
	SDL_PIXELFORMAT_RGBA5551 356782082
	SDL_PIXELFORMAT_ABGR1555 359862274
	SDL_PIXELFORMAT_BGRA5551 360976386
	SDL_PIXELFORMAT_RGB565 353701890
	SDL_PIXELFORMAT_BGR565 357896194
	SDL_PIXELFORMAT_RGB24 386930691
	SDL_PIXELFORMAT_BGR24 390076419
	SDL_PIXELFORMAT_XRGB8888 370546692
	SDL_PIXELFORMAT_RGBX8888 371595268
	SDL_PIXELFORMAT_XBGR8888 374740996
	SDL_PIXELFORMAT_BGRX8888 375789572
	SDL_PIXELFORMAT_ARGB8888 372645892
	SDL_PIXELFORMAT_RGBA8888 373694468
	SDL_PIXELFORMAT_ABGR8888 376840196
	SDL_PIXELFORMAT_BGRA8888 377888772
	SDL_PIXELFORMAT_XRGB2101010 370614276
	SDL_PIXELFORMAT_XBGR2101010 374808580
	SDL_PIXELFORMAT_ARGB2101010 372711428
	SDL_PIXELFORMAT_ABGR2101010 376905732
	SDL_PIXELFORMAT_RGB48 403714054
	SDL_PIXELFORMAT_BGR48 406859782
	SDL_PIXELFORMAT_RGBA64 404766728
	SDL_PIXELFORMAT_ARGB64 405815304
	SDL_PIXELFORMAT_BGRA64 407912456
	SDL_PIXELFORMAT_ABGR64 408961032
	SDL_PIXELFORMAT_RGB48_FLOAT 437268486
	SDL_PIXELFORMAT_BGR48_FLOAT 440414214
	SDL_PIXELFORMAT_RGBA64_FLOAT 438321160
	SDL_PIXELFORMAT_ARGB64_FLOAT 439369736
	SDL_PIXELFORMAT_BGRA64_FLOAT 441466888
	SDL_PIXELFORMAT_ABGR64_FLOAT 442515464
	SDL_PIXELFORMAT_RGB96_FLOAT 454057996
	SDL_PIXELFORMAT_BGR96_FLOAT 457203724
	SDL_PIXELFORMAT_RGBA128_FLOAT 455114768
	SDL_PIXELFORMAT_ARGB128_FLOAT 456163344
	SDL_PIXELFORMAT_BGRA128_FLOAT 458260496
	SDL_PIXELFORMAT_ABGR128_FLOAT 459309072
	SDL_PIXELFORMAT_YV12 842094169
	SDL_PIXELFORMAT_IYUV 1448433993
	SDL_PIXELFORMAT_YUY2 844715353
	SDL_PIXELFORMAT_UYVY 1498831189
	SDL_PIXELFORMAT_YVYU 1431918169
	SDL_PIXELFORMAT_NV12 842094158
	SDL_PIXELFORMAT_NV21 825382478
	SDL_PIXELFORMAT_P010 808530000
	SDL_PIXELFORMAT_EXTERNAL_OES 542328143
	SDL_PIXELFORMAT_MJPG 1196444237
	SDL_PIXELFORMAT_RGBA32 376840196
	SDL_PIXELFORMAT_ARGB32 377888772
	SDL_PIXELFORMAT_BGRA32 372645892
	SDL_PIXELFORMAT_ABGR32 373694468
	SDL_PIXELFORMAT_RGBX32 374740996
	SDL_PIXELFORMAT_XRGB32 375789572
	SDL_PIXELFORMAT_BGRX32 370546692
	SDL_PIXELFORMAT_XBGR32 371595268 )
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> externalOes [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_EXTERNAL_OES
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> index1lsb [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_INDEX1LSB
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> index1msb [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_INDEX1MSB
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> index2lsb [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_INDEX2LSB
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> index2msb [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_INDEX2MSB
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> index4lsb [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_INDEX4LSB
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> index4msb [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_INDEX4MSB
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> index8 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_INDEX8
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> iyuv [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_IYUV
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> mjpg [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_MJPG
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> nv12 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_NV12
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> nv21 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_NV21
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> p010 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_P010
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgb24 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGB24
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgb332 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGB332
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgb48 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGB48
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgb48Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGB48_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgb565 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGB565
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgb96Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGB96_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgba128Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBA128_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgba32 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBA32
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgba4444 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBA4444
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgba5551 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBA5551
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgba64 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBA64
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgba64Float [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBA64_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgba8888 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBA8888
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgbx32 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBX32
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> rgbx8888 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_RGBX8888
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> unknown [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_UNKNOWN
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> uyvy [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_UYVY
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xbgr1555 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XBGR1555
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xbgr2101010 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XBGR2101010
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xbgr32 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XBGR32
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xbgr4444 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XBGR4444
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xbgr8888 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XBGR8888
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xrgb1555 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XRGB1555
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xrgb2101010 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XRGB2101010
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xrgb32 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XRGB32
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xrgb4444 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XRGB4444
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> xrgb8888 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_XRGB8888
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> yuy2 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_YUY2
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> yv12 [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_YV12
]

{ #category : 'accessing enum' }
S3SDL_PixelFormat class >> yvyu [
	"This method was automatically generated"
	^ SDL_PIXELFORMAT_YVYU
]
