Class {
	#name : 'S3SDL_GPUVertexElementFormat',
	#superclass : 'S3Enumeration',
	#classVars : [
		'SDL_GPU_VERTEXELEMENTFORMAT_BYTE2',
		'SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM',
		'SDL_GPU_VERTEXELEMENTFORMAT_BYTE4',
		'SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM',
		'SDL_GPU_VERTEXELEMENTFORMAT_FLOAT',
		'SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2',
		'SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3',
		'SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4',
		'SDL_GPU_VERTEXELEMENTFORMAT_HALF2',
		'SDL_GPU_VERTEXELEMENTFORMAT_HALF4',
		'SDL_GPU_VERTEXELEMENTFORMAT_INT',
		'SDL_GPU_VERTEXELEMENTFORMAT_INT2',
		'SDL_GPU_VERTEXELEMENTFORMAT_INT3',
		'SDL_GPU_VERTEXELEMENTFORMAT_INT4',
		'SDL_GPU_VERTEXELEMENTFORMAT_INVALID',
		'SDL_GPU_VERTEXELEMENTFORMAT_SHORT2',
		'SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM',
		'SDL_GPU_VERTEXELEMENTFORMAT_SHORT4',
		'SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM',
		'SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2',
		'SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM',
		'SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4',
		'SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM',
		'SDL_GPU_VERTEXELEMENTFORMAT_UINT',
		'SDL_GPU_VERTEXELEMENTFORMAT_UINT2',
		'SDL_GPU_VERTEXELEMENTFORMAT_UINT3',
		'SDL_GPU_VERTEXELEMENTFORMAT_UINT4',
		'SDL_GPU_VERTEXELEMENTFORMAT_USHORT2',
		'SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM',
		'SDL_GPU_VERTEXELEMENTFORMAT_USHORT4',
		'SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM'
	],
	#category : 'SDL3-Base',
	#package : 'SDL3',
	#tag : 'Base'
}

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_BYTE2 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_BYTE2
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_BYTE4 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_BYTE4
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_FLOAT [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_FLOAT
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_HALF2 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_HALF2
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_HALF4 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_HALF4
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_INT [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_INT
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_INT2 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_INT2
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_INT3 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_INT3
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_INT4 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_INT4
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_INVALID [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_INVALID
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_SHORT2 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_SHORT2
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_SHORT4 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_SHORT4
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_UINT [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_UINT
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_UINT2 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_UINT2
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_UINT3 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_UINT3
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_UINT4 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_UINT4
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_USHORT2 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_USHORT2
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_USHORT4 [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_USHORT4
]

{ #category : 'accessing enum' }
S3SDL_GPUVertexElementFormat class >> SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM [
	"This method was automatically generated"
	^ SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM
]

{ #category : 'enum declaration' }
S3SDL_GPUVertexElementFormat class >> enumDecl [

	^ #(
	SDL_GPU_VERTEXELEMENTFORMAT_INVALID 0
	SDL_GPU_VERTEXELEMENTFORMAT_INT 1
	SDL_GPU_VERTEXELEMENTFORMAT_INT2 2
	SDL_GPU_VERTEXELEMENTFORMAT_INT3 3
	SDL_GPU_VERTEXELEMENTFORMAT_INT4 4
	SDL_GPU_VERTEXELEMENTFORMAT_UINT 5
	SDL_GPU_VERTEXELEMENTFORMAT_UINT2 6
	SDL_GPU_VERTEXELEMENTFORMAT_UINT3 7
	SDL_GPU_VERTEXELEMENTFORMAT_UINT4 8
	SDL_GPU_VERTEXELEMENTFORMAT_FLOAT 9
	SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2 10
	SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3 11
	SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4 12
	SDL_GPU_VERTEXELEMENTFORMAT_BYTE2 13
	SDL_GPU_VERTEXELEMENTFORMAT_BYTE4 14
	SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2 15
	SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4 16
	SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM 17
	SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM 18
	SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM 19
	SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM 20
	SDL_GPU_VERTEXELEMENTFORMAT_SHORT2 21
	SDL_GPU_VERTEXELEMENTFORMAT_SHORT4 22
	SDL_GPU_VERTEXELEMENTFORMAT_USHORT2 23
	SDL_GPU_VERTEXELEMENTFORMAT_USHORT4 24
	SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM 25
	SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM 26
	SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM 27
	SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM 28
	SDL_GPU_VERTEXELEMENTFORMAT_HALF2 29
	SDL_GPU_VERTEXELEMENTFORMAT_HALF4 30 )
]
