Class {
	#name : 'S3SDL_Scancode',
	#superclass : 'S3Enumeration',
	#classVars : [
		'SDL_SCANCODE_0',
		'SDL_SCANCODE_1',
		'SDL_SCANCODE_2',
		'SDL_SCANCODE_3',
		'SDL_SCANCODE_4',
		'SDL_SCANCODE_5',
		'SDL_SCANCODE_6',
		'SDL_SCANCODE_7',
		'SDL_SCANCODE_8',
		'SDL_SCANCODE_9',
		'SDL_SCANCODE_A',
		'SDL_SCANCODE_AC_BACK',
		'SDL_SCANCODE_AC_BOOKMARKS',
		'SDL_SCANCODE_AC_CLOSE',
		'SDL_SCANCODE_AC_EXIT',
		'SDL_SCANCODE_AC_FORWARD',
		'SDL_SCANCODE_AC_HOME',
		'SDL_SCANCODE_AC_NEW',
		'SDL_SCANCODE_AC_OPEN',
		'SDL_SCANCODE_AC_PRINT',
		'SDL_SCANCODE_AC_PROPERTIES',
		'SDL_SCANCODE_AC_REFRESH',
		'SDL_SCANCODE_AC_SAVE',
		'SDL_SCANCODE_AC_SEARCH',
		'SDL_SCANCODE_AC_STOP',
		'SDL_SCANCODE_AGAIN',
		'SDL_SCANCODE_ALTERASE',
		'SDL_SCANCODE_APOSTROPHE',
		'SDL_SCANCODE_APPLICATION',
		'SDL_SCANCODE_B',
		'SDL_SCANCODE_BACKSLASH',
		'SDL_SCANCODE_BACKSPACE',
		'SDL_SCANCODE_C',
		'SDL_SCANCODE_CALL',
		'SDL_SCANCODE_CANCEL',
		'SDL_SCANCODE_CAPSLOCK',
		'SDL_SCANCODE_CHANNEL_DECREMENT',
		'SDL_SCANCODE_CHANNEL_INCREMENT',
		'SDL_SCANCODE_CLEAR',
		'SDL_SCANCODE_CLEARAGAIN',
		'SDL_SCANCODE_COMMA',
		'SDL_SCANCODE_COPY',
		'SDL_SCANCODE_COUNT',
		'SDL_SCANCODE_CRSEL',
		'SDL_SCANCODE_CURRENCYSUBUNIT',
		'SDL_SCANCODE_CURRENCYUNIT',
		'SDL_SCANCODE_CUT',
		'SDL_SCANCODE_D',
		'SDL_SCANCODE_DECIMALSEPARATOR',
		'SDL_SCANCODE_DELETE',
		'SDL_SCANCODE_DOWN',
		'SDL_SCANCODE_E',
		'SDL_SCANCODE_END',
		'SDL_SCANCODE_ENDCALL',
		'SDL_SCANCODE_EQUALS',
		'SDL_SCANCODE_ESCAPE',
		'SDL_SCANCODE_EXECUTE',
		'SDL_SCANCODE_EXSEL',
		'SDL_SCANCODE_F',
		'SDL_SCANCODE_F1',
		'SDL_SCANCODE_F10',
		'SDL_SCANCODE_F11',
		'SDL_SCANCODE_F12',
		'SDL_SCANCODE_F13',
		'SDL_SCANCODE_F14',
		'SDL_SCANCODE_F15',
		'SDL_SCANCODE_F16',
		'SDL_SCANCODE_F17',
		'SDL_SCANCODE_F18',
		'SDL_SCANCODE_F19',
		'SDL_SCANCODE_F2',
		'SDL_SCANCODE_F20',
		'SDL_SCANCODE_F21',
		'SDL_SCANCODE_F22',
		'SDL_SCANCODE_F23',
		'SDL_SCANCODE_F24',
		'SDL_SCANCODE_F3',
		'SDL_SCANCODE_F4',
		'SDL_SCANCODE_F5',
		'SDL_SCANCODE_F6',
		'SDL_SCANCODE_F7',
		'SDL_SCANCODE_F8',
		'SDL_SCANCODE_F9',
		'SDL_SCANCODE_FIND',
		'SDL_SCANCODE_G',
		'SDL_SCANCODE_GRAVE',
		'SDL_SCANCODE_H',
		'SDL_SCANCODE_HELP',
		'SDL_SCANCODE_HOME',
		'SDL_SCANCODE_I',
		'SDL_SCANCODE_INSERT',
		'SDL_SCANCODE_INTERNATIONAL1',
		'SDL_SCANCODE_INTERNATIONAL2',
		'SDL_SCANCODE_INTERNATIONAL3',
		'SDL_SCANCODE_INTERNATIONAL4',
		'SDL_SCANCODE_INTERNATIONAL5',
		'SDL_SCANCODE_INTERNATIONAL6',
		'SDL_SCANCODE_INTERNATIONAL7',
		'SDL_SCANCODE_INTERNATIONAL8',
		'SDL_SCANCODE_INTERNATIONAL9',
		'SDL_SCANCODE_J',
		'SDL_SCANCODE_K',
		'SDL_SCANCODE_KP_0',
		'SDL_SCANCODE_KP_00',
		'SDL_SCANCODE_KP_000',
		'SDL_SCANCODE_KP_1',
		'SDL_SCANCODE_KP_2',
		'SDL_SCANCODE_KP_3',
		'SDL_SCANCODE_KP_4',
		'SDL_SCANCODE_KP_5',
		'SDL_SCANCODE_KP_6',
		'SDL_SCANCODE_KP_7',
		'SDL_SCANCODE_KP_8',
		'SDL_SCANCODE_KP_9',
		'SDL_SCANCODE_KP_A',
		'SDL_SCANCODE_KP_AMPERSAND',
		'SDL_SCANCODE_KP_AT',
		'SDL_SCANCODE_KP_B',
		'SDL_SCANCODE_KP_BACKSPACE',
		'SDL_SCANCODE_KP_BINARY',
		'SDL_SCANCODE_KP_C',
		'SDL_SCANCODE_KP_CLEAR',
		'SDL_SCANCODE_KP_CLEARENTRY',
		'SDL_SCANCODE_KP_COLON',
		'SDL_SCANCODE_KP_COMMA',
		'SDL_SCANCODE_KP_D',
		'SDL_SCANCODE_KP_DBLAMPERSAND',
		'SDL_SCANCODE_KP_DBLVERTICALBAR',
		'SDL_SCANCODE_KP_DECIMAL',
		'SDL_SCANCODE_KP_DIVIDE',
		'SDL_SCANCODE_KP_E',
		'SDL_SCANCODE_KP_ENTER',
		'SDL_SCANCODE_KP_EQUALS',
		'SDL_SCANCODE_KP_EQUALSAS400',
		'SDL_SCANCODE_KP_EXCLAM',
		'SDL_SCANCODE_KP_F',
		'SDL_SCANCODE_KP_GREATER',
		'SDL_SCANCODE_KP_HASH',
		'SDL_SCANCODE_KP_HEXADECIMAL',
		'SDL_SCANCODE_KP_LEFTBRACE',
		'SDL_SCANCODE_KP_LEFTPAREN',
		'SDL_SCANCODE_KP_LESS',
		'SDL_SCANCODE_KP_MEMADD',
		'SDL_SCANCODE_KP_MEMCLEAR',
		'SDL_SCANCODE_KP_MEMDIVIDE',
		'SDL_SCANCODE_KP_MEMMULTIPLY',
		'SDL_SCANCODE_KP_MEMRECALL',
		'SDL_SCANCODE_KP_MEMSTORE',
		'SDL_SCANCODE_KP_MEMSUBTRACT',
		'SDL_SCANCODE_KP_MINUS',
		'SDL_SCANCODE_KP_MULTIPLY',
		'SDL_SCANCODE_KP_OCTAL',
		'SDL_SCANCODE_KP_PERCENT',
		'SDL_SCANCODE_KP_PERIOD',
		'SDL_SCANCODE_KP_PLUS',
		'SDL_SCANCODE_KP_PLUSMINUS',
		'SDL_SCANCODE_KP_POWER',
		'SDL_SCANCODE_KP_RIGHTBRACE',
		'SDL_SCANCODE_KP_RIGHTPAREN',
		'SDL_SCANCODE_KP_SPACE',
		'SDL_SCANCODE_KP_TAB',
		'SDL_SCANCODE_KP_VERTICALBAR',
		'SDL_SCANCODE_KP_XOR',
		'SDL_SCANCODE_L',
		'SDL_SCANCODE_LALT',
		'SDL_SCANCODE_LANG1',
		'SDL_SCANCODE_LANG2',
		'SDL_SCANCODE_LANG3',
		'SDL_SCANCODE_LANG4',
		'SDL_SCANCODE_LANG5',
		'SDL_SCANCODE_LANG6',
		'SDL_SCANCODE_LANG7',
		'SDL_SCANCODE_LANG8',
		'SDL_SCANCODE_LANG9',
		'SDL_SCANCODE_LCTRL',
		'SDL_SCANCODE_LEFT',
		'SDL_SCANCODE_LEFTBRACKET',
		'SDL_SCANCODE_LGUI',
		'SDL_SCANCODE_LSHIFT',
		'SDL_SCANCODE_M',
		'SDL_SCANCODE_MEDIA_EJECT',
		'SDL_SCANCODE_MEDIA_FAST_FORWARD',
		'SDL_SCANCODE_MEDIA_NEXT_TRACK',
		'SDL_SCANCODE_MEDIA_PAUSE',
		'SDL_SCANCODE_MEDIA_PLAY',
		'SDL_SCANCODE_MEDIA_PLAY_PAUSE',
		'SDL_SCANCODE_MEDIA_PREVIOUS_TRACK',
		'SDL_SCANCODE_MEDIA_RECORD',
		'SDL_SCANCODE_MEDIA_REWIND',
		'SDL_SCANCODE_MEDIA_SELECT',
		'SDL_SCANCODE_MEDIA_STOP',
		'SDL_SCANCODE_MENU',
		'SDL_SCANCODE_MINUS',
		'SDL_SCANCODE_MODE',
		'SDL_SCANCODE_MUTE',
		'SDL_SCANCODE_N',
		'SDL_SCANCODE_NONUSBACKSLASH',
		'SDL_SCANCODE_NONUSHASH',
		'SDL_SCANCODE_NUMLOCKCLEAR',
		'SDL_SCANCODE_O',
		'SDL_SCANCODE_OPER',
		'SDL_SCANCODE_OUT',
		'SDL_SCANCODE_P',
		'SDL_SCANCODE_PAGEDOWN',
		'SDL_SCANCODE_PAGEUP',
		'SDL_SCANCODE_PASTE',
		'SDL_SCANCODE_PAUSE',
		'SDL_SCANCODE_PERIOD',
		'SDL_SCANCODE_POWER',
		'SDL_SCANCODE_PRINTSCREEN',
		'SDL_SCANCODE_PRIOR',
		'SDL_SCANCODE_Q',
		'SDL_SCANCODE_R',
		'SDL_SCANCODE_RALT',
		'SDL_SCANCODE_RCTRL',
		'SDL_SCANCODE_RESERVED',
		'SDL_SCANCODE_RETURN',
		'SDL_SCANCODE_RETURN2',
		'SDL_SCANCODE_RGUI',
		'SDL_SCANCODE_RIGHT',
		'SDL_SCANCODE_RIGHTBRACKET',
		'SDL_SCANCODE_RSHIFT',
		'SDL_SCANCODE_S',
		'SDL_SCANCODE_SCROLLLOCK',
		'SDL_SCANCODE_SELECT',
		'SDL_SCANCODE_SEMICOLON',
		'SDL_SCANCODE_SEPARATOR',
		'SDL_SCANCODE_SLASH',
		'SDL_SCANCODE_SLEEP',
		'SDL_SCANCODE_SOFTLEFT',
		'SDL_SCANCODE_SOFTRIGHT',
		'SDL_SCANCODE_SPACE',
		'SDL_SCANCODE_STOP',
		'SDL_SCANCODE_SYSREQ',
		'SDL_SCANCODE_T',
		'SDL_SCANCODE_TAB',
		'SDL_SCANCODE_THOUSANDSSEPARATOR',
		'SDL_SCANCODE_U',
		'SDL_SCANCODE_UNDO',
		'SDL_SCANCODE_UNKNOWN',
		'SDL_SCANCODE_UP',
		'SDL_SCANCODE_V',
		'SDL_SCANCODE_VOLUMEDOWN',
		'SDL_SCANCODE_VOLUMEUP',
		'SDL_SCANCODE_W',
		'SDL_SCANCODE_WAKE',
		'SDL_SCANCODE_X',
		'SDL_SCANCODE_Y',
		'SDL_SCANCODE_Z'
	],
	#category : 'SDL3-Base',
	#package : 'SDL3',
	#tag : 'Base'
}

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_0 [
	"This method was automatically generated"
	^ SDL_SCANCODE_0
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_1 [
	"This method was automatically generated"
	^ SDL_SCANCODE_1
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_2 [
	"This method was automatically generated"
	^ SDL_SCANCODE_2
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_3 [
	"This method was automatically generated"
	^ SDL_SCANCODE_3
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_4 [
	"This method was automatically generated"
	^ SDL_SCANCODE_4
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_5 [
	"This method was automatically generated"
	^ SDL_SCANCODE_5
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_6 [
	"This method was automatically generated"
	^ SDL_SCANCODE_6
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_7 [
	"This method was automatically generated"
	^ SDL_SCANCODE_7
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_8 [
	"This method was automatically generated"
	^ SDL_SCANCODE_8
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_9 [
	"This method was automatically generated"
	^ SDL_SCANCODE_9
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_A [
	"This method was automatically generated"
	^ SDL_SCANCODE_A
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_BACK [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_BACK
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_BOOKMARKS [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_BOOKMARKS
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_CLOSE [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_CLOSE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_EXIT [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_EXIT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_FORWARD [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_FORWARD
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_HOME [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_HOME
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_NEW [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_NEW
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_OPEN [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_OPEN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_PRINT [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_PRINT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_PROPERTIES [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_PROPERTIES
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_REFRESH [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_REFRESH
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_SAVE [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_SAVE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_SEARCH [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_SEARCH
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AC_STOP [
	"This method was automatically generated"
	^ SDL_SCANCODE_AC_STOP
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_AGAIN [
	"This method was automatically generated"
	^ SDL_SCANCODE_AGAIN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_ALTERASE [
	"This method was automatically generated"
	^ SDL_SCANCODE_ALTERASE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_APOSTROPHE [
	"This method was automatically generated"
	^ SDL_SCANCODE_APOSTROPHE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_APPLICATION [
	"This method was automatically generated"
	^ SDL_SCANCODE_APPLICATION
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_B [
	"This method was automatically generated"
	^ SDL_SCANCODE_B
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_BACKSLASH [
	"This method was automatically generated"
	^ SDL_SCANCODE_BACKSLASH
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_BACKSPACE [
	"This method was automatically generated"
	^ SDL_SCANCODE_BACKSPACE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_C [
	"This method was automatically generated"
	^ SDL_SCANCODE_C
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CALL [
	"This method was automatically generated"
	^ SDL_SCANCODE_CALL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CANCEL [
	"This method was automatically generated"
	^ SDL_SCANCODE_CANCEL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CAPSLOCK [
	"This method was automatically generated"
	^ SDL_SCANCODE_CAPSLOCK
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CHANNEL_DECREMENT [
	"This method was automatically generated"
	^ SDL_SCANCODE_CHANNEL_DECREMENT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CHANNEL_INCREMENT [
	"This method was automatically generated"
	^ SDL_SCANCODE_CHANNEL_INCREMENT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CLEAR [
	"This method was automatically generated"
	^ SDL_SCANCODE_CLEAR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CLEARAGAIN [
	"This method was automatically generated"
	^ SDL_SCANCODE_CLEARAGAIN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_COMMA [
	"This method was automatically generated"
	^ SDL_SCANCODE_COMMA
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_COPY [
	"This method was automatically generated"
	^ SDL_SCANCODE_COPY
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_COUNT [
	"This method was automatically generated"
	^ SDL_SCANCODE_COUNT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CRSEL [
	"This method was automatically generated"
	^ SDL_SCANCODE_CRSEL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CURRENCYSUBUNIT [
	"This method was automatically generated"
	^ SDL_SCANCODE_CURRENCYSUBUNIT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CURRENCYUNIT [
	"This method was automatically generated"
	^ SDL_SCANCODE_CURRENCYUNIT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_CUT [
	"This method was automatically generated"
	^ SDL_SCANCODE_CUT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_D [
	"This method was automatically generated"
	^ SDL_SCANCODE_D
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_DECIMALSEPARATOR [
	"This method was automatically generated"
	^ SDL_SCANCODE_DECIMALSEPARATOR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_DELETE [
	"This method was automatically generated"
	^ SDL_SCANCODE_DELETE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_DOWN [
	"This method was automatically generated"
	^ SDL_SCANCODE_DOWN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_E [
	"This method was automatically generated"
	^ SDL_SCANCODE_E
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_END [
	"This method was automatically generated"
	^ SDL_SCANCODE_END
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_ENDCALL [
	"This method was automatically generated"
	^ SDL_SCANCODE_ENDCALL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_EQUALS [
	"This method was automatically generated"
	^ SDL_SCANCODE_EQUALS
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_ESCAPE [
	"This method was automatically generated"
	^ SDL_SCANCODE_ESCAPE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_EXECUTE [
	"This method was automatically generated"
	^ SDL_SCANCODE_EXECUTE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_EXSEL [
	"This method was automatically generated"
	^ SDL_SCANCODE_EXSEL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F [
	"This method was automatically generated"
	^ SDL_SCANCODE_F
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F1 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F1
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F10 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F10
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F11 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F11
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F12 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F12
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F13 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F13
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F14 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F14
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F15 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F15
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F16 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F16
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F17 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F17
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F18 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F18
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F19 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F19
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F2 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F2
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F20 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F20
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F21 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F21
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F22 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F22
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F23 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F23
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F24 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F24
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F3 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F3
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F4 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F4
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F5 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F5
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F6 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F6
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F7 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F7
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F8 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F8
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_F9 [
	"This method was automatically generated"
	^ SDL_SCANCODE_F9
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_FIND [
	"This method was automatically generated"
	^ SDL_SCANCODE_FIND
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_G [
	"This method was automatically generated"
	^ SDL_SCANCODE_G
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_GRAVE [
	"This method was automatically generated"
	^ SDL_SCANCODE_GRAVE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_H [
	"This method was automatically generated"
	^ SDL_SCANCODE_H
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_HELP [
	"This method was automatically generated"
	^ SDL_SCANCODE_HELP
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_HOME [
	"This method was automatically generated"
	^ SDL_SCANCODE_HOME
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_I [
	"This method was automatically generated"
	^ SDL_SCANCODE_I
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INSERT [
	"This method was automatically generated"
	^ SDL_SCANCODE_INSERT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL1 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL1
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL2 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL2
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL3 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL3
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL4 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL4
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL5 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL5
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL6 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL6
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL7 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL7
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL8 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL8
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_INTERNATIONAL9 [
	"This method was automatically generated"
	^ SDL_SCANCODE_INTERNATIONAL9
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_J [
	"This method was automatically generated"
	^ SDL_SCANCODE_J
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_K [
	"This method was automatically generated"
	^ SDL_SCANCODE_K
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_0 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_0
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_00 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_00
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_000 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_000
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_1 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_1
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_2 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_2
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_3 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_3
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_4 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_4
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_5 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_5
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_6 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_6
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_7 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_7
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_8 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_8
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_9 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_9
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_A [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_A
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_AMPERSAND [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_AMPERSAND
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_AT [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_AT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_B [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_B
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_BACKSPACE [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_BACKSPACE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_BINARY [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_BINARY
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_C [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_C
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_CLEAR [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_CLEAR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_CLEARENTRY [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_CLEARENTRY
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_COLON [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_COLON
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_COMMA [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_COMMA
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_D [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_D
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_DBLAMPERSAND [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_DBLAMPERSAND
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_DBLVERTICALBAR [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_DBLVERTICALBAR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_DECIMAL [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_DECIMAL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_DIVIDE [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_DIVIDE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_E [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_E
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_ENTER [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_ENTER
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_EQUALS [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_EQUALS
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_EQUALSAS400 [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_EQUALSAS400
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_EXCLAM [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_EXCLAM
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_F [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_F
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_GREATER [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_GREATER
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_HASH [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_HASH
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_HEXADECIMAL [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_HEXADECIMAL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_LEFTBRACE [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_LEFTBRACE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_LEFTPAREN [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_LEFTPAREN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_LESS [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_LESS
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MEMADD [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MEMADD
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MEMCLEAR [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MEMCLEAR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MEMDIVIDE [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MEMDIVIDE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MEMMULTIPLY [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MEMMULTIPLY
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MEMRECALL [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MEMRECALL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MEMSTORE [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MEMSTORE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MEMSUBTRACT [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MEMSUBTRACT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MINUS [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MINUS
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_MULTIPLY [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_MULTIPLY
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_OCTAL [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_OCTAL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_PERCENT [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_PERCENT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_PERIOD [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_PERIOD
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_PLUS [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_PLUS
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_PLUSMINUS [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_PLUSMINUS
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_POWER [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_POWER
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_RIGHTBRACE [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_RIGHTBRACE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_RIGHTPAREN [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_RIGHTPAREN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_SPACE [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_SPACE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_TAB [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_TAB
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_VERTICALBAR [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_VERTICALBAR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_KP_XOR [
	"This method was automatically generated"
	^ SDL_SCANCODE_KP_XOR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_L [
	"This method was automatically generated"
	^ SDL_SCANCODE_L
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LALT [
	"This method was automatically generated"
	^ SDL_SCANCODE_LALT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG1 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG1
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG2 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG2
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG3 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG3
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG4 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG4
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG5 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG5
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG6 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG6
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG7 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG7
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG8 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG8
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LANG9 [
	"This method was automatically generated"
	^ SDL_SCANCODE_LANG9
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LCTRL [
	"This method was automatically generated"
	^ SDL_SCANCODE_LCTRL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LEFT [
	"This method was automatically generated"
	^ SDL_SCANCODE_LEFT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LEFTBRACKET [
	"This method was automatically generated"
	^ SDL_SCANCODE_LEFTBRACKET
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LGUI [
	"This method was automatically generated"
	^ SDL_SCANCODE_LGUI
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_LSHIFT [
	"This method was automatically generated"
	^ SDL_SCANCODE_LSHIFT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_M [
	"This method was automatically generated"
	^ SDL_SCANCODE_M
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_EJECT [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_EJECT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_FAST_FORWARD [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_FAST_FORWARD
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_NEXT_TRACK [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_NEXT_TRACK
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_PAUSE [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_PAUSE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_PLAY [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_PLAY
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_PLAY_PAUSE [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_PLAY_PAUSE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_PREVIOUS_TRACK [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_PREVIOUS_TRACK
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_RECORD [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_RECORD
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_REWIND [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_REWIND
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_SELECT [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_SELECT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MEDIA_STOP [
	"This method was automatically generated"
	^ SDL_SCANCODE_MEDIA_STOP
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MENU [
	"This method was automatically generated"
	^ SDL_SCANCODE_MENU
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MINUS [
	"This method was automatically generated"
	^ SDL_SCANCODE_MINUS
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MODE [
	"This method was automatically generated"
	^ SDL_SCANCODE_MODE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_MUTE [
	"This method was automatically generated"
	^ SDL_SCANCODE_MUTE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_N [
	"This method was automatically generated"
	^ SDL_SCANCODE_N
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_NONUSBACKSLASH [
	"This method was automatically generated"
	^ SDL_SCANCODE_NONUSBACKSLASH
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_NONUSHASH [
	"This method was automatically generated"
	^ SDL_SCANCODE_NONUSHASH
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_NUMLOCKCLEAR [
	"This method was automatically generated"
	^ SDL_SCANCODE_NUMLOCKCLEAR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_O [
	"This method was automatically generated"
	^ SDL_SCANCODE_O
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_OPER [
	"This method was automatically generated"
	^ SDL_SCANCODE_OPER
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_OUT [
	"This method was automatically generated"
	^ SDL_SCANCODE_OUT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_P [
	"This method was automatically generated"
	^ SDL_SCANCODE_P
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_PAGEDOWN [
	"This method was automatically generated"
	^ SDL_SCANCODE_PAGEDOWN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_PAGEUP [
	"This method was automatically generated"
	^ SDL_SCANCODE_PAGEUP
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_PASTE [
	"This method was automatically generated"
	^ SDL_SCANCODE_PASTE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_PAUSE [
	"This method was automatically generated"
	^ SDL_SCANCODE_PAUSE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_PERIOD [
	"This method was automatically generated"
	^ SDL_SCANCODE_PERIOD
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_POWER [
	"This method was automatically generated"
	^ SDL_SCANCODE_POWER
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_PRINTSCREEN [
	"This method was automatically generated"
	^ SDL_SCANCODE_PRINTSCREEN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_PRIOR [
	"This method was automatically generated"
	^ SDL_SCANCODE_PRIOR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_Q [
	"This method was automatically generated"
	^ SDL_SCANCODE_Q
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_R [
	"This method was automatically generated"
	^ SDL_SCANCODE_R
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RALT [
	"This method was automatically generated"
	^ SDL_SCANCODE_RALT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RCTRL [
	"This method was automatically generated"
	^ SDL_SCANCODE_RCTRL
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RESERVED [
	"This method was automatically generated"
	^ SDL_SCANCODE_RESERVED
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RETURN [
	"This method was automatically generated"
	^ SDL_SCANCODE_RETURN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RETURN2 [
	"This method was automatically generated"
	^ SDL_SCANCODE_RETURN2
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RGUI [
	"This method was automatically generated"
	^ SDL_SCANCODE_RGUI
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RIGHT [
	"This method was automatically generated"
	^ SDL_SCANCODE_RIGHT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RIGHTBRACKET [
	"This method was automatically generated"
	^ SDL_SCANCODE_RIGHTBRACKET
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_RSHIFT [
	"This method was automatically generated"
	^ SDL_SCANCODE_RSHIFT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_S [
	"This method was automatically generated"
	^ SDL_SCANCODE_S
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SCROLLLOCK [
	"This method was automatically generated"
	^ SDL_SCANCODE_SCROLLLOCK
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SELECT [
	"This method was automatically generated"
	^ SDL_SCANCODE_SELECT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SEMICOLON [
	"This method was automatically generated"
	^ SDL_SCANCODE_SEMICOLON
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SEPARATOR [
	"This method was automatically generated"
	^ SDL_SCANCODE_SEPARATOR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SLASH [
	"This method was automatically generated"
	^ SDL_SCANCODE_SLASH
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SLEEP [
	"This method was automatically generated"
	^ SDL_SCANCODE_SLEEP
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SOFTLEFT [
	"This method was automatically generated"
	^ SDL_SCANCODE_SOFTLEFT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SOFTRIGHT [
	"This method was automatically generated"
	^ SDL_SCANCODE_SOFTRIGHT
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SPACE [
	"This method was automatically generated"
	^ SDL_SCANCODE_SPACE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_STOP [
	"This method was automatically generated"
	^ SDL_SCANCODE_STOP
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_SYSREQ [
	"This method was automatically generated"
	^ SDL_SCANCODE_SYSREQ
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_T [
	"This method was automatically generated"
	^ SDL_SCANCODE_T
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_TAB [
	"This method was automatically generated"
	^ SDL_SCANCODE_TAB
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_THOUSANDSSEPARATOR [
	"This method was automatically generated"
	^ SDL_SCANCODE_THOUSANDSSEPARATOR
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_U [
	"This method was automatically generated"
	^ SDL_SCANCODE_U
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_UNDO [
	"This method was automatically generated"
	^ SDL_SCANCODE_UNDO
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_UNKNOWN [
	"This method was automatically generated"
	^ SDL_SCANCODE_UNKNOWN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_UP [
	"This method was automatically generated"
	^ SDL_SCANCODE_UP
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_V [
	"This method was automatically generated"
	^ SDL_SCANCODE_V
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_VOLUMEDOWN [
	"This method was automatically generated"
	^ SDL_SCANCODE_VOLUMEDOWN
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_VOLUMEUP [
	"This method was automatically generated"
	^ SDL_SCANCODE_VOLUMEUP
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_W [
	"This method was automatically generated"
	^ SDL_SCANCODE_W
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_WAKE [
	"This method was automatically generated"
	^ SDL_SCANCODE_WAKE
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_X [
	"This method was automatically generated"
	^ SDL_SCANCODE_X
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_Y [
	"This method was automatically generated"
	^ SDL_SCANCODE_Y
]

{ #category : 'accessing enum' }
S3SDL_Scancode class >> SDL_SCANCODE_Z [
	"This method was automatically generated"
	^ SDL_SCANCODE_Z
]

{ #category : 'enum declaration' }
S3SDL_Scancode class >> enumDecl [

	^ #(
	SDL_SCANCODE_UNKNOWN 0
	SDL_SCANCODE_A 4
	SDL_SCANCODE_B 5
	SDL_SCANCODE_C 6
	SDL_SCANCODE_D 7
	SDL_SCANCODE_E 8
	SDL_SCANCODE_F 9
	SDL_SCANCODE_G 10
	SDL_SCANCODE_H 11
	SDL_SCANCODE_I 12
	SDL_SCANCODE_J 13
	SDL_SCANCODE_K 14
	SDL_SCANCODE_L 15
	SDL_SCANCODE_M 16
	SDL_SCANCODE_N 17
	SDL_SCANCODE_O 18
	SDL_SCANCODE_P 19
	SDL_SCANCODE_Q 20
	SDL_SCANCODE_R 21
	SDL_SCANCODE_S 22
	SDL_SCANCODE_T 23
	SDL_SCANCODE_U 24
	SDL_SCANCODE_V 25
	SDL_SCANCODE_W 26
	SDL_SCANCODE_X 27
	SDL_SCANCODE_Y 28
	SDL_SCANCODE_Z 29
	SDL_SCANCODE_1 30
	SDL_SCANCODE_2 31
	SDL_SCANCODE_3 32
	SDL_SCANCODE_4 33
	SDL_SCANCODE_5 34
	SDL_SCANCODE_6 35
	SDL_SCANCODE_7 36
	SDL_SCANCODE_8 37
	SDL_SCANCODE_9 38
	SDL_SCANCODE_0 39
	SDL_SCANCODE_RETURN 40
	SDL_SCANCODE_ESCAPE 41
	SDL_SCANCODE_BACKSPACE 42
	SDL_SCANCODE_TAB 43
	SDL_SCANCODE_SPACE 44
	SDL_SCANCODE_MINUS 45
	SDL_SCANCODE_EQUALS 46
	SDL_SCANCODE_LEFTBRACKET 47
	SDL_SCANCODE_RIGHTBRACKET 48
	SDL_SCANCODE_BACKSLASH 49
	SDL_SCANCODE_NONUSHASH 50
	SDL_SCANCODE_SEMICOLON 51
	SDL_SCANCODE_APOSTROPHE 52
	SDL_SCANCODE_GRAVE 53
	SDL_SCANCODE_COMMA 54
	SDL_SCANCODE_PERIOD 55
	SDL_SCANCODE_SLASH 56
	SDL_SCANCODE_CAPSLOCK 57
	SDL_SCANCODE_F1 58
	SDL_SCANCODE_F2 59
	SDL_SCANCODE_F3 60
	SDL_SCANCODE_F4 61
	SDL_SCANCODE_F5 62
	SDL_SCANCODE_F6 63
	SDL_SCANCODE_F7 64
	SDL_SCANCODE_F8 65
	SDL_SCANCODE_F9 66
	SDL_SCANCODE_F10 67
	SDL_SCANCODE_F11 68
	SDL_SCANCODE_F12 69
	SDL_SCANCODE_PRINTSCREEN 70
	SDL_SCANCODE_SCROLLLOCK 71
	SDL_SCANCODE_PAUSE 72
	SDL_SCANCODE_INSERT 73
	SDL_SCANCODE_HOME 74
	SDL_SCANCODE_PAGEUP 75
	SDL_SCANCODE_DELETE 76
	SDL_SCANCODE_END 77
	SDL_SCANCODE_PAGEDOWN 78
	SDL_SCANCODE_RIGHT 79
	SDL_SCANCODE_LEFT 80
	SDL_SCANCODE_DOWN 81
	SDL_SCANCODE_UP 82
	SDL_SCANCODE_NUMLOCKCLEAR 83
	SDL_SCANCODE_KP_DIVIDE 84
	SDL_SCANCODE_KP_MULTIPLY 85
	SDL_SCANCODE_KP_MINUS 86
	SDL_SCANCODE_KP_PLUS 87
	SDL_SCANCODE_KP_ENTER 88
	SDL_SCANCODE_KP_1 89
	SDL_SCANCODE_KP_2 90
	SDL_SCANCODE_KP_3 91
	SDL_SCANCODE_KP_4 92
	SDL_SCANCODE_KP_5 93
	SDL_SCANCODE_KP_6 94
	SDL_SCANCODE_KP_7 95
	SDL_SCANCODE_KP_8 96
	SDL_SCANCODE_KP_9 97
	SDL_SCANCODE_KP_0 98
	SDL_SCANCODE_KP_PERIOD 99
	SDL_SCANCODE_NONUSBACKSLASH 100
	SDL_SCANCODE_APPLICATION 101
	SDL_SCANCODE_POWER 102
	SDL_SCANCODE_KP_EQUALS 103
	SDL_SCANCODE_F13 104
	SDL_SCANCODE_F14 105
	SDL_SCANCODE_F15 106
	SDL_SCANCODE_F16 107
	SDL_SCANCODE_F17 108
	SDL_SCANCODE_F18 109
	SDL_SCANCODE_F19 110
	SDL_SCANCODE_F20 111
	SDL_SCANCODE_F21 112
	SDL_SCANCODE_F22 113
	SDL_SCANCODE_F23 114
	SDL_SCANCODE_F24 115
	SDL_SCANCODE_EXECUTE 116
	SDL_SCANCODE_HELP 117
	SDL_SCANCODE_MENU 118
	SDL_SCANCODE_SELECT 119
	SDL_SCANCODE_STOP 120
	SDL_SCANCODE_AGAIN 121
	SDL_SCANCODE_UNDO 122
	SDL_SCANCODE_CUT 123
	SDL_SCANCODE_COPY 124
	SDL_SCANCODE_PASTE 125
	SDL_SCANCODE_FIND 126
	SDL_SCANCODE_MUTE 127
	SDL_SCANCODE_VOLUMEUP 128
	SDL_SCANCODE_VOLUMEDOWN 129
	SDL_SCANCODE_KP_COMMA 133
	SDL_SCANCODE_KP_EQUALSAS400 134
	SDL_SCANCODE_INTERNATIONAL1 135
	SDL_SCANCODE_INTERNATIONAL2 136
	SDL_SCANCODE_INTERNATIONAL3 137
	SDL_SCANCODE_INTERNATIONAL4 138
	SDL_SCANCODE_INTERNATIONAL5 139
	SDL_SCANCODE_INTERNATIONAL6 140
	SDL_SCANCODE_INTERNATIONAL7 141
	SDL_SCANCODE_INTERNATIONAL8 142
	SDL_SCANCODE_INTERNATIONAL9 143
	SDL_SCANCODE_LANG1 144
	SDL_SCANCODE_LANG2 145
	SDL_SCANCODE_LANG3 146
	SDL_SCANCODE_LANG4 147
	SDL_SCANCODE_LANG5 148
	SDL_SCANCODE_LANG6 149
	SDL_SCANCODE_LANG7 150
	SDL_SCANCODE_LANG8 151
	SDL_SCANCODE_LANG9 152
	SDL_SCANCODE_ALTERASE 153
	SDL_SCANCODE_SYSREQ 154
	SDL_SCANCODE_CANCEL 155
	SDL_SCANCODE_CLEAR 156
	SDL_SCANCODE_PRIOR 157
	SDL_SCANCODE_RETURN2 158
	SDL_SCANCODE_SEPARATOR 159
	SDL_SCANCODE_OUT 160
	SDL_SCANCODE_OPER 161
	SDL_SCANCODE_CLEARAGAIN 162
	SDL_SCANCODE_CRSEL 163
	SDL_SCANCODE_EXSEL 164
	SDL_SCANCODE_KP_00 176
	SDL_SCANCODE_KP_000 177
	SDL_SCANCODE_THOUSANDSSEPARATOR 178
	SDL_SCANCODE_DECIMALSEPARATOR 179
	SDL_SCANCODE_CURRENCYUNIT 180
	SDL_SCANCODE_CURRENCYSUBUNIT 181
	SDL_SCANCODE_KP_LEFTPAREN 182
	SDL_SCANCODE_KP_RIGHTPAREN 183
	SDL_SCANCODE_KP_LEFTBRACE 184
	SDL_SCANCODE_KP_RIGHTBRACE 185
	SDL_SCANCODE_KP_TAB 186
	SDL_SCANCODE_KP_BACKSPACE 187
	SDL_SCANCODE_KP_A 188
	SDL_SCANCODE_KP_B 189
	SDL_SCANCODE_KP_C 190
	SDL_SCANCODE_KP_D 191
	SDL_SCANCODE_KP_E 192
	SDL_SCANCODE_KP_F 193
	SDL_SCANCODE_KP_XOR 194
	SDL_SCANCODE_KP_POWER 195
	SDL_SCANCODE_KP_PERCENT 196
	SDL_SCANCODE_KP_LESS 197
	SDL_SCANCODE_KP_GREATER 198
	SDL_SCANCODE_KP_AMPERSAND 199
	SDL_SCANCODE_KP_DBLAMPERSAND 200
	SDL_SCANCODE_KP_VERTICALBAR 201
	SDL_SCANCODE_KP_DBLVERTICALBAR 202
	SDL_SCANCODE_KP_COLON 203
	SDL_SCANCODE_KP_HASH 204
	SDL_SCANCODE_KP_SPACE 205
	SDL_SCANCODE_KP_AT 206
	SDL_SCANCODE_KP_EXCLAM 207
	SDL_SCANCODE_KP_MEMSTORE 208
	SDL_SCANCODE_KP_MEMRECALL 209
	SDL_SCANCODE_KP_MEMCLEAR 210
	SDL_SCANCODE_KP_MEMADD 211
	SDL_SCANCODE_KP_MEMSUBTRACT 212
	SDL_SCANCODE_KP_MEMMULTIPLY 213
	SDL_SCANCODE_KP_MEMDIVIDE 214
	SDL_SCANCODE_KP_PLUSMINUS 215
	SDL_SCANCODE_KP_CLEAR 216
	SDL_SCANCODE_KP_CLEARENTRY 217
	SDL_SCANCODE_KP_BINARY 218
	SDL_SCANCODE_KP_OCTAL 219
	SDL_SCANCODE_KP_DECIMAL 220
	SDL_SCANCODE_KP_HEXADECIMAL 221
	SDL_SCANCODE_LCTRL 224
	SDL_SCANCODE_LSHIFT 225
	SDL_SCANCODE_LALT 226
	SDL_SCANCODE_LGUI 227
	SDL_SCANCODE_RCTRL 228
	SDL_SCANCODE_RSHIFT 229
	SDL_SCANCODE_RALT 230
	SDL_SCANCODE_RGUI 231
	SDL_SCANCODE_MODE 257
	SDL_SCANCODE_SLEEP 258
	SDL_SCANCODE_WAKE 259
	SDL_SCANCODE_CHANNEL_INCREMENT 260
	SDL_SCANCODE_CHANNEL_DECREMENT 261
	SDL_SCANCODE_MEDIA_PLAY 262
	SDL_SCANCODE_MEDIA_PAUSE 263
	SDL_SCANCODE_MEDIA_RECORD 264
	SDL_SCANCODE_MEDIA_FAST_FORWARD 265
	SDL_SCANCODE_MEDIA_REWIND 266
	SDL_SCANCODE_MEDIA_NEXT_TRACK 267
	SDL_SCANCODE_MEDIA_PREVIOUS_TRACK 268
	SDL_SCANCODE_MEDIA_STOP 269
	SDL_SCANCODE_MEDIA_EJECT 270
	SDL_SCANCODE_MEDIA_PLAY_PAUSE 271
	SDL_SCANCODE_MEDIA_SELECT 272
	SDL_SCANCODE_AC_NEW 273
	SDL_SCANCODE_AC_OPEN 274
	SDL_SCANCODE_AC_CLOSE 275
	SDL_SCANCODE_AC_EXIT 276
	SDL_SCANCODE_AC_SAVE 277
	SDL_SCANCODE_AC_PRINT 278
	SDL_SCANCODE_AC_PROPERTIES 279
	SDL_SCANCODE_AC_SEARCH 280
	SDL_SCANCODE_AC_HOME 281
	SDL_SCANCODE_AC_BACK 282
	SDL_SCANCODE_AC_FORWARD 283
	SDL_SCANCODE_AC_STOP 284
	SDL_SCANCODE_AC_REFRESH 285
	SDL_SCANCODE_AC_BOOKMARKS 286
	SDL_SCANCODE_SOFTLEFT 287
	SDL_SCANCODE_SOFTRIGHT 288
	SDL_SCANCODE_CALL 289
	SDL_SCANCODE_ENDCALL 290
	SDL_SCANCODE_RESERVED 400
	SDL_SCANCODE_COUNT 512 )
]
