Class {
	#name : 'S3SDL_EventType',
	#superclass : 'S3Enumeration',
	#classVars : [
		'SDL_EVENT_AUDIO_DEVICE_ADDED',
		'SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED',
		'SDL_EVENT_AUDIO_DEVICE_REMOVED',
		'SDL_EVENT_CAMERA_DEVICE_ADDED',
		'SDL_EVENT_CAMERA_DEVICE_APPROVED',
		'SDL_EVENT_CAMERA_DEVICE_DENIED',
		'SDL_EVENT_CAMERA_DEVICE_REMOVED',
		'SDL_EVENT_CLIPBOARD_UPDATE',
		'SDL_EVENT_DID_ENTER_BACKGROUND',
		'SDL_EVENT_DID_ENTER_FOREGROUND',
		'SDL_EVENT_DISPLAY_ADDED',
		'SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED',
		'SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED',
		'SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED',
		'SDL_EVENT_DISPLAY_FIRST',
		'SDL_EVENT_DISPLAY_LAST',
		'SDL_EVENT_DISPLAY_MOVED',
		'SDL_EVENT_DISPLAY_ORIENTATION',
		'SDL_EVENT_DISPLAY_REMOVED',
		'SDL_EVENT_DROP_BEGIN',
		'SDL_EVENT_DROP_COMPLETE',
		'SDL_EVENT_DROP_FILE',
		'SDL_EVENT_DROP_POSITION',
		'SDL_EVENT_DROP_TEXT',
		'SDL_EVENT_ENUM_PADDING',
		'SDL_EVENT_FINGER_CANCELED',
		'SDL_EVENT_FINGER_DOWN',
		'SDL_EVENT_FINGER_MOTION',
		'SDL_EVENT_FINGER_UP',
		'SDL_EVENT_FIRST',
		'SDL_EVENT_GAMEPAD_ADDED',
		'SDL_EVENT_GAMEPAD_AXIS_MOTION',
		'SDL_EVENT_GAMEPAD_BUTTON_DOWN',
		'SDL_EVENT_GAMEPAD_BUTTON_UP',
		'SDL_EVENT_GAMEPAD_REMAPPED',
		'SDL_EVENT_GAMEPAD_REMOVED',
		'SDL_EVENT_GAMEPAD_SENSOR_UPDATE',
		'SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED',
		'SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN',
		'SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION',
		'SDL_EVENT_GAMEPAD_TOUCHPAD_UP',
		'SDL_EVENT_GAMEPAD_UPDATE_COMPLETE',
		'SDL_EVENT_JOYSTICK_ADDED',
		'SDL_EVENT_JOYSTICK_AXIS_MOTION',
		'SDL_EVENT_JOYSTICK_BALL_MOTION',
		'SDL_EVENT_JOYSTICK_BATTERY_UPDATED',
		'SDL_EVENT_JOYSTICK_BUTTON_DOWN',
		'SDL_EVENT_JOYSTICK_BUTTON_UP',
		'SDL_EVENT_JOYSTICK_HAT_MOTION',
		'SDL_EVENT_JOYSTICK_REMOVED',
		'SDL_EVENT_JOYSTICK_UPDATE_COMPLETE',
		'SDL_EVENT_KEYBOARD_ADDED',
		'SDL_EVENT_KEYBOARD_REMOVED',
		'SDL_EVENT_KEYMAP_CHANGED',
		'SDL_EVENT_KEY_DOWN',
		'SDL_EVENT_KEY_UP',
		'SDL_EVENT_LAST',
		'SDL_EVENT_LOCALE_CHANGED',
		'SDL_EVENT_LOW_MEMORY',
		'SDL_EVENT_MOUSE_ADDED',
		'SDL_EVENT_MOUSE_BUTTON_DOWN',
		'SDL_EVENT_MOUSE_BUTTON_UP',
		'SDL_EVENT_MOUSE_MOTION',
		'SDL_EVENT_MOUSE_REMOVED',
		'SDL_EVENT_MOUSE_WHEEL',
		'SDL_EVENT_PEN_AXIS',
		'SDL_EVENT_PEN_BUTTON_DOWN',
		'SDL_EVENT_PEN_BUTTON_UP',
		'SDL_EVENT_PEN_DOWN',
		'SDL_EVENT_PEN_MOTION',
		'SDL_EVENT_PEN_PROXIMITY_IN',
		'SDL_EVENT_PEN_PROXIMITY_OUT',
		'SDL_EVENT_PEN_UP',
		'SDL_EVENT_POLL_SENTINEL',
		'SDL_EVENT_PRIVATE0',
		'SDL_EVENT_PRIVATE1',
		'SDL_EVENT_PRIVATE2',
		'SDL_EVENT_PRIVATE3',
		'SDL_EVENT_QUIT',
		'SDL_EVENT_RENDER_DEVICE_LOST',
		'SDL_EVENT_RENDER_DEVICE_RESET',
		'SDL_EVENT_RENDER_TARGETS_RESET',
		'SDL_EVENT_SENSOR_UPDATE',
		'SDL_EVENT_SYSTEM_THEME_CHANGED',
		'SDL_EVENT_TERMINATING',
		'SDL_EVENT_TEXT_EDITING',
		'SDL_EVENT_TEXT_EDITING_CANDIDATES',
		'SDL_EVENT_TEXT_INPUT',
		'SDL_EVENT_USER',
		'SDL_EVENT_WILL_ENTER_BACKGROUND',
		'SDL_EVENT_WILL_ENTER_FOREGROUND',
		'SDL_EVENT_WINDOW_CLOSE_REQUESTED',
		'SDL_EVENT_WINDOW_DESTROYED',
		'SDL_EVENT_WINDOW_DISPLAY_CHANGED',
		'SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED',
		'SDL_EVENT_WINDOW_ENTER_FULLSCREEN',
		'SDL_EVENT_WINDOW_EXPOSED',
		'SDL_EVENT_WINDOW_FIRST',
		'SDL_EVENT_WINDOW_FOCUS_GAINED',
		'SDL_EVENT_WINDOW_FOCUS_LOST',
		'SDL_EVENT_WINDOW_HDR_STATE_CHANGED',
		'SDL_EVENT_WINDOW_HIDDEN',
		'SDL_EVENT_WINDOW_HIT_TEST',
		'SDL_EVENT_WINDOW_ICCPROF_CHANGED',
		'SDL_EVENT_WINDOW_LAST',
		'SDL_EVENT_WINDOW_LEAVE_FULLSCREEN',
		'SDL_EVENT_WINDOW_MAXIMIZED',
		'SDL_EVENT_WINDOW_METAL_VIEW_RESIZED',
		'SDL_EVENT_WINDOW_MINIMIZED',
		'SDL_EVENT_WINDOW_MOUSE_ENTER',
		'SDL_EVENT_WINDOW_MOUSE_LEAVE',
		'SDL_EVENT_WINDOW_MOVED',
		'SDL_EVENT_WINDOW_OCCLUDED',
		'SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED',
		'SDL_EVENT_WINDOW_RESIZED',
		'SDL_EVENT_WINDOW_RESTORED',
		'SDL_EVENT_WINDOW_SAFE_AREA_CHANGED',
		'SDL_EVENT_WINDOW_SHOWN'
	],
	#category : 'SDL3-Base',
	#package : 'SDL3',
	#tag : 'Base'
}

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_AUDIO_DEVICE_ADDED [
	"This method was automatically generated"
	^ SDL_EVENT_AUDIO_DEVICE_ADDED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_AUDIO_DEVICE_REMOVED [
	"This method was automatically generated"
	^ SDL_EVENT_AUDIO_DEVICE_REMOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_CAMERA_DEVICE_ADDED [
	"This method was automatically generated"
	^ SDL_EVENT_CAMERA_DEVICE_ADDED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_CAMERA_DEVICE_APPROVED [
	"This method was automatically generated"
	^ SDL_EVENT_CAMERA_DEVICE_APPROVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_CAMERA_DEVICE_DENIED [
	"This method was automatically generated"
	^ SDL_EVENT_CAMERA_DEVICE_DENIED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_CAMERA_DEVICE_REMOVED [
	"This method was automatically generated"
	^ SDL_EVENT_CAMERA_DEVICE_REMOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_CLIPBOARD_UPDATE [
	"This method was automatically generated"
	^ SDL_EVENT_CLIPBOARD_UPDATE
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DID_ENTER_BACKGROUND [
	"This method was automatically generated"
	^ SDL_EVENT_DID_ENTER_BACKGROUND
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DID_ENTER_FOREGROUND [
	"This method was automatically generated"
	^ SDL_EVENT_DID_ENTER_FOREGROUND
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DISPLAY_ADDED [
	"This method was automatically generated"
	^ SDL_EVENT_DISPLAY_ADDED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DISPLAY_MOVED [
	"This method was automatically generated"
	^ SDL_EVENT_DISPLAY_MOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DISPLAY_ORIENTATION [
	"This method was automatically generated"
	^ SDL_EVENT_DISPLAY_ORIENTATION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DISPLAY_REMOVED [
	"This method was automatically generated"
	^ SDL_EVENT_DISPLAY_REMOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DROP_BEGIN [
	"This method was automatically generated"
	^ SDL_EVENT_DROP_BEGIN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DROP_COMPLETE [
	"This method was automatically generated"
	^ SDL_EVENT_DROP_COMPLETE
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DROP_FILE [
	"This method was automatically generated"
	^ SDL_EVENT_DROP_FILE
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DROP_POSITION [
	"This method was automatically generated"
	^ SDL_EVENT_DROP_POSITION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_DROP_TEXT [
	"This method was automatically generated"
	^ SDL_EVENT_DROP_TEXT
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_ENUM_PADDING [
	"This method was automatically generated"
	^ SDL_EVENT_ENUM_PADDING
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_FINGER_CANCELED [
	"This method was automatically generated"
	^ SDL_EVENT_FINGER_CANCELED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_FINGER_DOWN [
	"This method was automatically generated"
	^ SDL_EVENT_FINGER_DOWN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_FINGER_MOTION [
	"This method was automatically generated"
	^ SDL_EVENT_FINGER_MOTION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_FINGER_UP [
	"This method was automatically generated"
	^ SDL_EVENT_FINGER_UP
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_ADDED [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_ADDED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_AXIS_MOTION [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_AXIS_MOTION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_BUTTON_DOWN [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_BUTTON_DOWN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_BUTTON_UP [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_BUTTON_UP
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_REMAPPED [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_REMAPPED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_REMOVED [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_REMOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_SENSOR_UPDATE [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_SENSOR_UPDATE
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_TOUCHPAD_UP [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_TOUCHPAD_UP
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_GAMEPAD_UPDATE_COMPLETE [
	"This method was automatically generated"
	^ SDL_EVENT_GAMEPAD_UPDATE_COMPLETE
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_ADDED [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_ADDED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_AXIS_MOTION [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_AXIS_MOTION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_BALL_MOTION [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_BALL_MOTION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_BATTERY_UPDATED [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_BATTERY_UPDATED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_BUTTON_DOWN [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_BUTTON_DOWN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_BUTTON_UP [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_BUTTON_UP
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_HAT_MOTION [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_HAT_MOTION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_REMOVED [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_REMOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_JOYSTICK_UPDATE_COMPLETE [
	"This method was automatically generated"
	^ SDL_EVENT_JOYSTICK_UPDATE_COMPLETE
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_KEYBOARD_ADDED [
	"This method was automatically generated"
	^ SDL_EVENT_KEYBOARD_ADDED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_KEYBOARD_REMOVED [
	"This method was automatically generated"
	^ SDL_EVENT_KEYBOARD_REMOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_KEYMAP_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_KEYMAP_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_KEY_DOWN [
	"This method was automatically generated"
	^ SDL_EVENT_KEY_DOWN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_KEY_UP [
	"This method was automatically generated"
	^ SDL_EVENT_KEY_UP
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_LOCALE_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_LOCALE_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_LOW_MEMORY [
	"This method was automatically generated"
	^ SDL_EVENT_LOW_MEMORY
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_MOUSE_ADDED [
	"This method was automatically generated"
	^ SDL_EVENT_MOUSE_ADDED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_MOUSE_BUTTON_DOWN [
	"This method was automatically generated"
	^ SDL_EVENT_MOUSE_BUTTON_DOWN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_MOUSE_BUTTON_UP [
	"This method was automatically generated"
	^ SDL_EVENT_MOUSE_BUTTON_UP
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_MOUSE_MOTION [
	"This method was automatically generated"
	^ SDL_EVENT_MOUSE_MOTION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_MOUSE_REMOVED [
	"This method was automatically generated"
	^ SDL_EVENT_MOUSE_REMOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_MOUSE_WHEEL [
	"This method was automatically generated"
	^ SDL_EVENT_MOUSE_WHEEL
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PEN_AXIS [
	"This method was automatically generated"
	^ SDL_EVENT_PEN_AXIS
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PEN_BUTTON_DOWN [
	"This method was automatically generated"
	^ SDL_EVENT_PEN_BUTTON_DOWN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PEN_BUTTON_UP [
	"This method was automatically generated"
	^ SDL_EVENT_PEN_BUTTON_UP
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PEN_DOWN [
	"This method was automatically generated"
	^ SDL_EVENT_PEN_DOWN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PEN_MOTION [
	"This method was automatically generated"
	^ SDL_EVENT_PEN_MOTION
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PEN_PROXIMITY_IN [
	"This method was automatically generated"
	^ SDL_EVENT_PEN_PROXIMITY_IN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PEN_PROXIMITY_OUT [
	"This method was automatically generated"
	^ SDL_EVENT_PEN_PROXIMITY_OUT
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PEN_UP [
	"This method was automatically generated"
	^ SDL_EVENT_PEN_UP
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_POLL_SENTINEL [
	"This method was automatically generated"
	^ SDL_EVENT_POLL_SENTINEL
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PRIVATE0 [
	"This method was automatically generated"
	^ SDL_EVENT_PRIVATE0
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PRIVATE1 [
	"This method was automatically generated"
	^ SDL_EVENT_PRIVATE1
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PRIVATE2 [
	"This method was automatically generated"
	^ SDL_EVENT_PRIVATE2
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_PRIVATE3 [
	"This method was automatically generated"
	^ SDL_EVENT_PRIVATE3
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_QUIT [
	"This method was automatically generated"
	^ SDL_EVENT_QUIT
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_RENDER_DEVICE_LOST [
	"This method was automatically generated"
	^ SDL_EVENT_RENDER_DEVICE_LOST
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_RENDER_DEVICE_RESET [
	"This method was automatically generated"
	^ SDL_EVENT_RENDER_DEVICE_RESET
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_RENDER_TARGETS_RESET [
	"This method was automatically generated"
	^ SDL_EVENT_RENDER_TARGETS_RESET
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_SENSOR_UPDATE [
	"This method was automatically generated"
	^ SDL_EVENT_SENSOR_UPDATE
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_SYSTEM_THEME_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_SYSTEM_THEME_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_TERMINATING [
	"This method was automatically generated"
	^ SDL_EVENT_TERMINATING
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_TEXT_EDITING [
	"This method was automatically generated"
	^ SDL_EVENT_TEXT_EDITING
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_TEXT_EDITING_CANDIDATES [
	"This method was automatically generated"
	^ SDL_EVENT_TEXT_EDITING_CANDIDATES
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_TEXT_INPUT [
	"This method was automatically generated"
	^ SDL_EVENT_TEXT_INPUT
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_USER [
	"This method was automatically generated"
	^ SDL_EVENT_USER
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WILL_ENTER_BACKGROUND [
	"This method was automatically generated"
	^ SDL_EVENT_WILL_ENTER_BACKGROUND
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WILL_ENTER_FOREGROUND [
	"This method was automatically generated"
	^ SDL_EVENT_WILL_ENTER_FOREGROUND
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_CLOSE_REQUESTED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_CLOSE_REQUESTED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_DESTROYED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_DESTROYED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_DISPLAY_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_DISPLAY_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_ENTER_FULLSCREEN [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_ENTER_FULLSCREEN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_EXPOSED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_EXPOSED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_FOCUS_GAINED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_FOCUS_GAINED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_FOCUS_LOST [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_FOCUS_LOST
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_HDR_STATE_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_HDR_STATE_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_HIDDEN [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_HIDDEN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_HIT_TEST [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_HIT_TEST
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_ICCPROF_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_ICCPROF_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_LEAVE_FULLSCREEN [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_LEAVE_FULLSCREEN
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_MAXIMIZED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_MAXIMIZED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_METAL_VIEW_RESIZED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_METAL_VIEW_RESIZED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_MINIMIZED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_MINIMIZED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_MOUSE_ENTER [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_MOUSE_ENTER
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_MOUSE_LEAVE [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_MOUSE_LEAVE
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_MOVED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_MOVED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_OCCLUDED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_OCCLUDED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_RESIZED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_RESIZED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_RESTORED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_RESTORED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_SAFE_AREA_CHANGED [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_SAFE_AREA_CHANGED
]

{ #category : 'accessing enum' }
S3SDL_EventType class >> SDL_EVENT_WINDOW_SHOWN [
	"This method was automatically generated"
	^ SDL_EVENT_WINDOW_SHOWN
]
