Class {
	#name : 'SDL3ZConstants',
	#superclass : 'SharedPool',
	#pools : [
		'SDL3ButtonConstants',
		'SDL3EndianConstants',
		'SDL3HapticConstants',
		'SDL3HintConstants',
		'SDL3InitConstants',
		'SDL3JoystickConstants',
		'SDL3KeyConstants',
		'SDL3KeyModifierConstants',
		'SDL3MessageBoxConstants',
		'SDL3PropertyConstants',
		'SDL3TrayEntryConstants',
		'SDL3VersionConstants',
		'SDL3VideoConstants',
		'SDL3WindowConstants'
	],
	#category : 'SDL3-Library',
	#package : 'SDL3',
	#tag : 'Library'
}
