"
Bindings for `SDL_Keycode` constants in `SDL_keycode.h`, in SDL3 3.3.0.

This class isn't generated automatically, it's manual. Why? SDL3 doesn't define these flags as an enumeration but as `#define` macros.
"
Class {
	#name : 'SDL3Keycode',
	#superclass : 'SDL3MacroDefinedFlag',
	#classVars : [
		'SDLK_0',
		'SDLK_1',
		'SDLK_2',
		'SDLK_3',
		'SDLK_4',
		'SDLK_5',
		'SDLK_6',
		'SDLK_7',
		'SDLK_8',
		'SDLK_9',
		'SDLK_A',
		'SDLK_AC_BACK',
		'SDLK_AC_BOOKMARKS',
		'SDLK_AC_CLOSE',
		'SDLK_AC_EXIT',
		'SDLK_AC_FORWARD',
		'SDLK_AC_HOME',
		'SDLK_AC_NEW',
		'SDLK_AC_OPEN',
		'SDLK_AC_PRINT',
		'SDLK_AC_PROPERTIES',
		'SDLK_AC_REFRESH',
		'SDLK_AC_SAVE',
		'SDLK_AC_SEARCH',
		'SDLK_AC_STOP',
		'SDLK_AGAIN',
		'SDLK_ALTERASE',
		'SDLK_AMPERSAND',
		'SDLK_APOSTROPHE',
		'SDLK_APPLICATION',
		'SDLK_ASTERISK',
		'SDLK_AT',
		'SDLK_B',
		'SDLK_BACKSLASH',
		'SDLK_BACKSPACE',
		'SDLK_C',
		'SDLK_CALL',
		'SDLK_CANCEL',
		'SDLK_CAPSLOCK',
		'SDLK_CARET',
		'SDLK_CHANNEL_DECREMENT',
		'SDLK_CHANNEL_INCREMENT',
		'SDLK_CLEAR',
		'SDLK_CLEARAGAIN',
		'SDLK_COLON',
		'SDLK_COMMA',
		'SDLK_COPY',
		'SDLK_CRSEL',
		'SDLK_CURRENCYSUBUNIT',
		'SDLK_CURRENCYUNIT',
		'SDLK_CUT',
		'SDLK_D',
		'SDLK_DBLAPOSTROPHE',
		'SDLK_DECIMALSEPARATOR',
		'SDLK_DELETE',
		'SDLK_DOLLAR',
		'SDLK_DOWN',
		'SDLK_E',
		'SDLK_END',
		'SDLK_ENDCALL',
		'SDLK_EQUALS',
		'SDLK_ESCAPE',
		'SDLK_EXCLAIM',
		'SDLK_EXECUTE',
		'SDLK_EXSEL',
		'SDLK_F',
		'SDLK_F1',
		'SDLK_F10',
		'SDLK_F11',
		'SDLK_F12',
		'SDLK_F13',
		'SDLK_F14',
		'SDLK_F15',
		'SDLK_F16',
		'SDLK_F17',
		'SDLK_F18',
		'SDLK_F19',
		'SDLK_F2',
		'SDLK_F20',
		'SDLK_F21',
		'SDLK_F22',
		'SDLK_F23',
		'SDLK_F24',
		'SDLK_F3',
		'SDLK_F4',
		'SDLK_F5',
		'SDLK_F6',
		'SDLK_F7',
		'SDLK_F8',
		'SDLK_F9',
		'SDLK_FIND',
		'SDLK_G',
		'SDLK_GRAVE',
		'SDLK_GREATER',
		'SDLK_H',
		'SDLK_HASH',
		'SDLK_HELP',
		'SDLK_HOME',
		'SDLK_I',
		'SDLK_INSERT',
		'SDLK_J',
		'SDLK_K',
		'SDLK_KP_0',
		'SDLK_KP_00',
		'SDLK_KP_000',
		'SDLK_KP_1',
		'SDLK_KP_2',
		'SDLK_KP_3',
		'SDLK_KP_4',
		'SDLK_KP_5',
		'SDLK_KP_6',
		'SDLK_KP_7',
		'SDLK_KP_8',
		'SDLK_KP_9',
		'SDLK_KP_A',
		'SDLK_KP_AMPERSAND',
		'SDLK_KP_AT',
		'SDLK_KP_B',
		'SDLK_KP_BACKSPACE',
		'SDLK_KP_BINARY',
		'SDLK_KP_C',
		'SDLK_KP_CLEAR',
		'SDLK_KP_CLEARENTRY',
		'SDLK_KP_COLON',
		'SDLK_KP_COMMA',
		'SDLK_KP_D',
		'SDLK_KP_DBLAMPERSAND',
		'SDLK_KP_DBLVERTICALBAR',
		'SDLK_KP_DECIMAL',
		'SDLK_KP_DIVIDE',
		'SDLK_KP_E',
		'SDLK_KP_ENTER',
		'SDLK_KP_EQUALS',
		'SDLK_KP_EQUALSAS400',
		'SDLK_KP_EXCLAM',
		'SDLK_KP_F',
		'SDLK_KP_GREATER',
		'SDLK_KP_HASH',
		'SDLK_KP_HEXADECIMAL',
		'SDLK_KP_LEFTBRACE',
		'SDLK_KP_LEFTPAREN',
		'SDLK_KP_LESS',
		'SDLK_KP_MEMADD',
		'SDLK_KP_MEMCLEAR',
		'SDLK_KP_MEMDIVIDE',
		'SDLK_KP_MEMMULTIPLY',
		'SDLK_KP_MEMRECALL',
		'SDLK_KP_MEMSTORE',
		'SDLK_KP_MEMSUBTRACT',
		'SDLK_KP_MINUS',
		'SDLK_KP_MULTIPLY',
		'SDLK_KP_OCTAL',
		'SDLK_KP_PERCENT',
		'SDLK_KP_PERIOD',
		'SDLK_KP_PLUS',
		'SDLK_KP_PLUSMINUS',
		'SDLK_KP_POWER',
		'SDLK_KP_RIGHTBRACE',
		'SDLK_KP_RIGHTPAREN',
		'SDLK_KP_SPACE',
		'SDLK_KP_TAB',
		'SDLK_KP_VERTICALBAR',
		'SDLK_KP_XOR',
		'SDLK_L',
		'SDLK_LALT',
		'SDLK_LCTRL',
		'SDLK_LEFT',
		'SDLK_LEFTBRACE',
		'SDLK_LEFTBRACKET',
		'SDLK_LEFTPAREN',
		'SDLK_LEFT_TAB',
		'SDLK_LESS',
		'SDLK_LEVEL5_SHIFT',
		'SDLK_LGUI',
		'SDLK_LHYPER',
		'SDLK_LMETA',
		'SDLK_LSHIFT',
		'SDLK_M',
		'SDLK_MEDIA_EJECT',
		'SDLK_MEDIA_FAST_FORWARD',
		'SDLK_MEDIA_NEXT_TRACK',
		'SDLK_MEDIA_PAUSE',
		'SDLK_MEDIA_PLAY',
		'SDLK_MEDIA_PLAY_PAUSE',
		'SDLK_MEDIA_PREVIOUS_TRACK',
		'SDLK_MEDIA_RECORD',
		'SDLK_MEDIA_REWIND',
		'SDLK_MEDIA_SELECT',
		'SDLK_MEDIA_STOP',
		'SDLK_MENU',
		'SDLK_MINUS',
		'SDLK_MODE',
		'SDLK_MULTI_KEY_COMPOSE',
		'SDLK_MUTE',
		'SDLK_N',
		'SDLK_NUMLOCKCLEAR',
		'SDLK_O',
		'SDLK_OPER',
		'SDLK_OUT',
		'SDLK_P',
		'SDLK_PAGEDOWN',
		'SDLK_PAGEUP',
		'SDLK_PASTE',
		'SDLK_PAUSE',
		'SDLK_PERCENT',
		'SDLK_PERIOD',
		'SDLK_PIPE',
		'SDLK_PLUS',
		'SDLK_PLUSMINUS',
		'SDLK_POWER',
		'SDLK_PRINTSCREEN',
		'SDLK_PRIOR',
		'SDLK_Q',
		'SDLK_QUESTION',
		'SDLK_R',
		'SDLK_RALT',
		'SDLK_RCTRL',
		'SDLK_RETURN',
		'SDLK_RETURN2',
		'SDLK_RGUI',
		'SDLK_RHYPER',
		'SDLK_RIGHT',
		'SDLK_RIGHTBRACE',
		'SDLK_RIGHTBRACKET',
		'SDLK_RIGHTPAREN',
		'SDLK_RMETA',
		'SDLK_RSHIFT',
		'SDLK_S',
		'SDLK_SCROLLLOCK',
		'SDLK_SELECT',
		'SDLK_SEMICOLON',
		'SDLK_SEPARATOR',
		'SDLK_SLASH',
		'SDLK_SLEEP',
		'SDLK_SOFTLEFT',
		'SDLK_SOFTRIGHT',
		'SDLK_SPACE',
		'SDLK_STOP',
		'SDLK_SYSREQ',
		'SDLK_T',
		'SDLK_TAB',
		'SDLK_THOUSANDSSEPARATOR',
		'SDLK_TILDE',
		'SDLK_U',
		'SDLK_UNDERSCORE',
		'SDLK_UNDO',
		'SDLK_UNKNOWN',
		'SDLK_UP',
		'SDLK_V',
		'SDLK_VOLUMEDOWN',
		'SDLK_VOLUMEUP',
		'SDLK_W',
		'SDLK_WAKE',
		'SDLK_X',
		'SDLK_Y',
		'SDLK_Z'
	],
	#category : 'SDL3-Own',
	#package : 'SDL3-Own'
}

{ #category : 'accessing enum' }
SDL3Keycode class >> a [
	"This method was automatically generated"
	^ SDLK_A
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acBack [
	"This method was automatically generated"
	^ SDLK_AC_BACK
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acBookmarks [
	"This method was automatically generated"
	^ SDLK_AC_BOOKMARKS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acClose [
	"This method was automatically generated"
	^ SDLK_AC_CLOSE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acExit [
	"This method was automatically generated"
	^ SDLK_AC_EXIT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acForward [
	"This method was automatically generated"
	^ SDLK_AC_FORWARD
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acHome [
	"This method was automatically generated"
	^ SDLK_AC_HOME
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acNew [
	"This method was automatically generated"
	^ SDLK_AC_NEW
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acOpen [
	"This method was automatically generated"
	^ SDLK_AC_OPEN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acPrint [
	"This method was automatically generated"
	^ SDLK_AC_PRINT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acProperties [
	"This method was automatically generated"
	^ SDLK_AC_PROPERTIES
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acRefresh [
	"This method was automatically generated"
	^ SDLK_AC_REFRESH
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acSave [
	"This method was automatically generated"
	^ SDLK_AC_SAVE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acSearch [
	"This method was automatically generated"
	^ SDLK_AC_SEARCH
]

{ #category : 'accessing enum' }
SDL3Keycode class >> acStop [
	"This method was automatically generated"
	^ SDLK_AC_STOP
]

{ #category : 'accessing enum' }
SDL3Keycode class >> again [
	"This method was automatically generated"
	^ SDLK_AGAIN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> alterase [
	"This method was automatically generated"
	^ SDLK_ALTERASE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> ampersand [
	"This method was automatically generated"
	^ SDLK_AMPERSAND
]

{ #category : 'accessing enum' }
SDL3Keycode class >> apostrophe [
	"This method was automatically generated"
	^ SDLK_APOSTROPHE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> application [
	"This method was automatically generated"
	^ SDLK_APPLICATION
]

{ #category : 'accessing enum' }
SDL3Keycode class >> asterisk [
	"This method was automatically generated"
	^ SDLK_ASTERISK
]

{ #category : 'accessing enum' }
SDL3Keycode class >> at [
	"This method was automatically generated"
	^ SDLK_AT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> b [
	"This method was automatically generated"
	^ SDLK_B
]

{ #category : 'accessing enum' }
SDL3Keycode class >> backslash [
	"This method was automatically generated"
	^ SDLK_BACKSLASH
]

{ #category : 'accessing enum' }
SDL3Keycode class >> backspace [
	"This method was automatically generated"
	^ SDLK_BACKSPACE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> c [
	"This method was automatically generated"
	^ SDLK_C
]

{ #category : 'accessing enum' }
SDL3Keycode class >> call [
	"This method was automatically generated"
	^ SDLK_CALL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> cancel [
	"This method was automatically generated"
	^ SDLK_CANCEL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> capsLock [
	"This method was automatically generated"
	^ SDLK_CAPSLOCK
]

{ #category : 'accessing enum' }
SDL3Keycode class >> caret [
	"This method was automatically generated"
	^ SDLK_CARET
]

{ #category : 'accessing enum' }
SDL3Keycode class >> channelDecrement [
	"This method was automatically generated"
	^ SDLK_CHANNEL_DECREMENT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> channelIncrement [
	"This method was automatically generated"
	^ SDLK_CHANNEL_INCREMENT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> clear [
	"This method was automatically generated"
	^ SDLK_CLEAR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> clearAgain [
	"This method was automatically generated"
	^ SDLK_CLEARAGAIN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> colon [
	"This method was automatically generated"
	^ SDLK_COLON
]

{ #category : 'accessing enum' }
SDL3Keycode class >> comma [
	"This method was automatically generated"
	^ SDLK_COMMA
]

{ #category : 'accessing enum' }
SDL3Keycode class >> copy [
	"This method was automatically generated"
	^ SDLK_COPY
]

{ #category : 'accessing enum' }
SDL3Keycode class >> crsel [
	"This method was automatically generated"
	^ SDLK_CRSEL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> currencyUnit [
	"This method was automatically generated"
	^ SDLK_CURRENCYUNIT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> currencysubUnit [
	"This method was automatically generated"
	^ SDLK_CURRENCYSUBUNIT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> cut [
	"This method was automatically generated"
	^ SDLK_CUT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> d [
	"This method was automatically generated"
	^ SDLK_D
]

{ #category : 'accessing enum' }
SDL3Keycode class >> decimalSeparator [
	"This method was automatically generated"
	^ SDLK_DECIMALSEPARATOR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> delete [
	"This method was automatically generated"
	^ SDLK_DELETE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> dollar [
	"This method was automatically generated"
	^ SDLK_DOLLAR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> doubleApostrophe [
	"This method was automatically generated"
	^ SDLK_DBLAPOSTROPHE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> down [
	"This method was automatically generated"
	^ SDLK_DOWN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> e [
	"This method was automatically generated"
	^ SDLK_E
]

{ #category : 'accessing enum' }
SDL3Keycode class >> end [
	"This method was automatically generated"
	^ SDLK_END
]

{ #category : 'accessing enum' }
SDL3Keycode class >> endcall [
	"This method was automatically generated"
	^ SDLK_ENDCALL
]

{ #category : 'enum declaration' }
SDL3Keycode class >> enumDecl [
	"Generate API from scratch:
	
	SDL3Keycode initializeEnumeration; rebuildEnumAccessors.
	
	enumClass := SDL3Keycode.
	renames := enumClass enumDeclToCamelCaseDictionary.

	""Apply rename refactorings""
	env := RBPackageEnvironment packageNames: #('SDL3-Own').
	env := env & (RBSelectorEnvironment new addMethod: (enumClass classSide >> #enumDecl); yourself) not.
	model := RBNamespace onEnvironment: env.

	allChanges := OrderedCollection new.
	renames keysAndValuesDo: [ :oldName :newName |
		allChanges addAll: (ReRenameMethodRefactoring new
	        model: model;
	        renameMethod: oldName
	        	in: enumClass classSide
				to: newName
				permutation: #();
	        renameChanges) changes ].

	allChanges := allChanges reject: [ :e |
		e class = RBAddMethodChange and: [
			""e protocol ~= #'accessing enum'""
			(e selector beginsWith: 'enumDecl') and: [ 
				e changeClassName = enumClass name ] ] ].

	allChanges do: #generateChanges.
"
	
	^ #(
		SDLK_UNKNOWN                16r00000000
		SDLK_RETURN                 16r0000000d
		SDLK_ESCAPE                 16r0000001b
		SDLK_BACKSPACE              16r00000008
		SDLK_TAB                    16r00000009
		SDLK_SPACE                  16r00000020
		SDLK_EXCLAIM                16r00000021
		SDLK_DBLAPOSTROPHE          16r00000022
		SDLK_HASH                   16r00000023
		SDLK_DOLLAR                 16r00000024
		SDLK_PERCENT                16r00000025
		SDLK_AMPERSAND              16r00000026
		SDLK_APOSTROPHE             16r00000027
		SDLK_LEFTPAREN              16r00000028
		SDLK_RIGHTPAREN             16r00000029
		SDLK_ASTERISK               16r0000002a
		SDLK_PLUS                   16r0000002b
		SDLK_COMMA                  16r0000002c
		SDLK_MINUS                  16r0000002d
		SDLK_PERIOD                 16r0000002e
		SDLK_SLASH                  16r0000002f
		SDLK_0                      16r00000030
		SDLK_1                      16r00000031
		SDLK_2                      16r00000032
		SDLK_3                      16r00000033
		SDLK_4                      16r00000034
		SDLK_5                      16r00000035
		SDLK_6                      16r00000036
		SDLK_7                      16r00000037
		SDLK_8                      16r00000038
		SDLK_9                      16r00000039
		SDLK_COLON                  16r0000003a
		SDLK_SEMICOLON              16r0000003b
		SDLK_LESS                   16r0000003c
		SDLK_EQUALS                 16r0000003d
		SDLK_GREATER                16r0000003e
		SDLK_QUESTION               16r0000003f
		SDLK_AT                     16r00000040
		SDLK_LEFTBRACKET            16r0000005b
		SDLK_BACKSLASH              16r0000005c
		SDLK_RIGHTBRACKET           16r0000005d
		SDLK_CARET                  16r0000005e
		SDLK_UNDERSCORE             16r0000005f
		SDLK_GRAVE                  16r00000060
		SDLK_A                      16r00000061
		SDLK_B                      16r00000062
		SDLK_C                      16r00000063
		SDLK_D                      16r00000064
		SDLK_E                      16r00000065
		SDLK_F                      16r00000066
		SDLK_G                      16r00000067
		SDLK_H                      16r00000068
		SDLK_I                      16r00000069
		SDLK_J                      16r0000006a
		SDLK_K                      16r0000006b
		SDLK_L                      16r0000006c
		SDLK_M                      16r0000006d
		SDLK_N                      16r0000006e
		SDLK_O                      16r0000006f
		SDLK_P                      16r00000070
		SDLK_Q                      16r00000071
		SDLK_R                      16r00000072
		SDLK_S                      16r00000073
		SDLK_T                      16r00000074
		SDLK_U                      16r00000075
		SDLK_V                      16r00000076
		SDLK_W                      16r00000077
		SDLK_X                      16r00000078
		SDLK_Y                      16r00000079
		SDLK_Z                      16r0000007a
		SDLK_LEFTBRACE              16r0000007b
		SDLK_PIPE                   16r0000007c
		SDLK_RIGHTBRACE             16r0000007d
		SDLK_TILDE                  16r0000007e
		SDLK_DELETE                 16r0000007f
		SDLK_PLUSMINUS              16r000000b1
		SDLK_CAPSLOCK               16r40000039
		SDLK_F1                     16r4000003a
		SDLK_F2                     16r4000003b
		SDLK_F3                     16r4000003c
		SDLK_F4                     16r4000003d
		SDLK_F5                     16r4000003e
		SDLK_F6                     16r4000003f
		SDLK_F7                     16r40000040
		SDLK_F8                     16r40000041
		SDLK_F9                     16r40000042
		SDLK_F10                    16r40000043
		SDLK_F11                    16r40000044
		SDLK_F12                    16r40000045
		SDLK_PRINTSCREEN            16r40000046
		SDLK_SCROLLLOCK             16r40000047
		SDLK_PAUSE                  16r40000048
		SDLK_INSERT                 16r40000049
		SDLK_HOME                   16r4000004a
		SDLK_PAGEUP                 16r4000004b
		SDLK_END                    16r4000004d
		SDLK_PAGEDOWN               16r4000004e
		SDLK_RIGHT                  16r4000004f
		SDLK_LEFT                   16r40000050
		SDLK_DOWN                   16r40000051
		SDLK_UP                     16r40000052
		SDLK_NUMLOCKCLEAR           16r40000053
		SDLK_KP_DIVIDE              16r40000054
		SDLK_KP_MULTIPLY            16r40000055
		SDLK_KP_MINUS               16r40000056
		SDLK_KP_PLUS                16r40000057
		SDLK_KP_ENTER               16r40000058
		SDLK_KP_1                   16r40000059
		SDLK_KP_2                   16r4000005a
		SDLK_KP_3                   16r4000005b
		SDLK_KP_4                   16r4000005c
		SDLK_KP_5                   16r4000005d
		SDLK_KP_6                   16r4000005e
		SDLK_KP_7                   16r4000005f
		SDLK_KP_8                   16r40000060
		SDLK_KP_9                   16r40000061
		SDLK_KP_0                   16r40000062
		SDLK_KP_PERIOD              16r40000063
		SDLK_APPLICATION            16r40000065
		SDLK_POWER                  16r40000066
		SDLK_KP_EQUALS              16r40000067
		SDLK_F13                    16r40000068
		SDLK_F14                    16r40000069
		SDLK_F15                    16r4000006a
		SDLK_F16                    16r4000006b
		SDLK_F17                    16r4000006c
		SDLK_F18                    16r4000006d
		SDLK_F19                    16r4000006e
		SDLK_F20                    16r4000006f
		SDLK_F21                    16r40000070
		SDLK_F22                    16r40000071
		SDLK_F23                    16r40000072
		SDLK_F24                    16r40000073
		SDLK_EXECUTE                16r40000074
		SDLK_HELP                   16r40000075
		SDLK_MENU                   16r40000076
		SDLK_SELECT                 16r40000077
		SDLK_STOP                   16r40000078
		SDLK_AGAIN                  16r40000079
		SDLK_UNDO                   16r4000007a
		SDLK_CUT                    16r4000007b
		SDLK_COPY                   16r4000007c
		SDLK_PASTE                  16r4000007d
		SDLK_FIND                   16r4000007e
		SDLK_MUTE                   16r4000007f
		SDLK_VOLUMEUP               16r40000080
		SDLK_VOLUMEDOWN             16r40000081
		SDLK_KP_COMMA               16r40000085
		SDLK_KP_EQUALSAS400         16r40000086
		SDLK_ALTERASE               16r40000099
		SDLK_SYSREQ                 16r4000009a
		SDLK_CANCEL                 16r4000009b
		SDLK_CLEAR                  16r4000009c
		SDLK_PRIOR                  16r4000009d
		SDLK_RETURN2                16r4000009e
		SDLK_SEPARATOR              16r4000009f
		SDLK_OUT                    16r400000a0
		SDLK_OPER                   16r400000a1
		SDLK_CLEARAGAIN             16r400000a2
		SDLK_CRSEL                  16r400000a3
		SDLK_EXSEL                  16r400000a4
		SDLK_KP_00                  16r400000b0
		SDLK_KP_000                 16r400000b1
		SDLK_THOUSANDSSEPARATOR     16r400000b2
		SDLK_DECIMALSEPARATOR       16r400000b3
		SDLK_CURRENCYUNIT           16r400000b4
		SDLK_CURRENCYSUBUNIT        16r400000b5
		SDLK_KP_LEFTPAREN           16r400000b6
		SDLK_KP_RIGHTPAREN          16r400000b7
		SDLK_KP_LEFTBRACE           16r400000b8
		SDLK_KP_RIGHTBRACE          16r400000b9
		SDLK_KP_TAB                 16r400000ba
		SDLK_KP_BACKSPACE           16r400000bb
		SDLK_KP_A                   16r400000bc
		SDLK_KP_B                   16r400000bd
		SDLK_KP_C                   16r400000be
		SDLK_KP_D                   16r400000bf
		SDLK_KP_E                   16r400000c0
		SDLK_KP_F                   16r400000c1
		SDLK_KP_XOR                 16r400000c2
		SDLK_KP_POWER               16r400000c3
		SDLK_KP_PERCENT             16r400000c4
		SDLK_KP_LESS                16r400000c5
		SDLK_KP_GREATER             16r400000c6
		SDLK_KP_AMPERSAND           16r400000c7
		SDLK_KP_DBLAMPERSAND        16r400000c8
		SDLK_KP_VERTICALBAR         16r400000c9
		SDLK_KP_DBLVERTICALBAR      16r400000ca
		SDLK_KP_COLON               16r400000cb
		SDLK_KP_HASH                16r400000cc
		SDLK_KP_SPACE               16r400000cd
		SDLK_KP_AT                  16r400000ce
		SDLK_KP_EXCLAM              16r400000cf
		SDLK_KP_MEMSTORE            16r400000d0
		SDLK_KP_MEMRECALL           16r400000d1
		SDLK_KP_MEMCLEAR            16r400000d2
		SDLK_KP_MEMADD              16r400000d3
		SDLK_KP_MEMSUBTRACT         16r400000d4
		SDLK_KP_MEMMULTIPLY         16r400000d5
		SDLK_KP_MEMDIVIDE           16r400000d6
		SDLK_KP_PLUSMINUS           16r400000d7
		SDLK_KP_CLEAR               16r400000d8
		SDLK_KP_CLEARENTRY          16r400000d9
		SDLK_KP_BINARY              16r400000da
		SDLK_KP_OCTAL               16r400000db
		SDLK_KP_DECIMAL             16r400000dc
		SDLK_KP_HEXADECIMAL         16r400000dd
		SDLK_LCTRL                  16r400000e0
		SDLK_LSHIFT                 16r400000e1
		SDLK_LALT                   16r400000e2
		SDLK_LGUI                   16r400000e3
		SDLK_RCTRL                  16r400000e4
		SDLK_RSHIFT                 16r400000e5
		SDLK_RALT                   16r400000e6
		SDLK_RGUI                   16r400000e7
		SDLK_MODE                   16r40000101
		SDLK_SLEEP                  16r40000102
		SDLK_WAKE                   16r40000103
		SDLK_CHANNEL_INCREMENT      16r40000104
		SDLK_CHANNEL_DECREMENT      16r40000105
		SDLK_MEDIA_PLAY             16r40000106
		SDLK_MEDIA_PAUSE            16r40000107
		SDLK_MEDIA_RECORD           16r40000108
		SDLK_MEDIA_FAST_FORWARD     16r40000109
		SDLK_MEDIA_REWIND           16r4000010a
		SDLK_MEDIA_NEXT_TRACK       16r4000010b
		SDLK_MEDIA_PREVIOUS_TRACK   16r4000010c
		SDLK_MEDIA_STOP             16r4000010d
		SDLK_MEDIA_EJECT            16r4000010e
		SDLK_MEDIA_PLAY_PAUSE       16r4000010f
		SDLK_MEDIA_SELECT           16r40000110
		SDLK_AC_NEW                 16r40000111
		SDLK_AC_OPEN                16r40000112
		SDLK_AC_CLOSE               16r40000113
		SDLK_AC_EXIT                16r40000114
		SDLK_AC_SAVE                16r40000115
		SDLK_AC_PRINT               16r40000116
		SDLK_AC_PROPERTIES          16r40000117
		SDLK_AC_SEARCH              16r40000118
		SDLK_AC_HOME                16r40000119
		SDLK_AC_BACK                16r4000011a
		SDLK_AC_FORWARD             16r4000011b
		SDLK_AC_STOP                16r4000011c
		SDLK_AC_REFRESH             16r4000011d
		SDLK_AC_BOOKMARKS           16r4000011e
		SDLK_SOFTLEFT               16r4000011f
		SDLK_SOFTRIGHT              16r40000120
		SDLK_CALL                   16r40000121
		SDLK_ENDCALL                16r40000122
		SDLK_LEFT_TAB               16r20000001
		SDLK_LEVEL5_SHIFT           16r20000002
		SDLK_MULTI_KEY_COMPOSE      16r20000003
		SDLK_LMETA                  16r20000004
		SDLK_RMETA                  16r20000005
		SDLK_LHYPER                 16r20000006
		SDLK_RHYPER                 16r20000007)
]

{ #category : 'enum declaration' }
SDL3Keycode class >> enumDeclToCamelCaseAt: aName prefix: prefix givenInvalidName: invalidName [

	invalidName first isDigit ifFalse: [ self error ].

	^ 'number', invalidName
]

{ #category : 'enum declaration' }
SDL3Keycode class >> enumDeclToCamelCaseDictionary [
	"
	self enumDeclToCamelCaseDictionary
	"
	| dict |
	dict := super enumDeclToCamelCaseDictionary.

	dict associations do: [ :assoc |

		(assoc value beginsWith: 'kp') ifTrue: [
			dict at: assoc key put: ('keypad', (assoc value withoutPrefix: 'kp') capitalized) ].

		(assoc value endsWith: 'paren') ifTrue: [
			dict at: assoc key put: ((assoc value withoutSuffix: 'paren'), 'Parenthesis') ].

		#(brace bracket up down left right lock separator unit again minus colon) do: [ :suffix |
			(assoc value endsWith: suffix) ifTrue: [
				dict
					at: assoc key
					put: ((assoc value withoutSuffix: suffix), suffix capitalized) uncapitalized ] ].

		(assoc value includesSubstring: 'dbl' caseSensitive: false) ifTrue: [
			| index |
			index := assoc value findString: 'dbl' startingAt: 1 caseSensitive: false.
			dict
				at: assoc key
				put:
					((assoc value first: index - 1),
					'Double',
					(assoc value allButFirst: index + 'dbl' size - 1) capitalized)
						uncapitalized ].
		].


	dict
		at: #SDLK_HASH put: #hashKey; "avoid overriding #hash"
		at: #SDLK_LMETA put: #leftMeta;
		at: #SDLK_RMETA put: #rightMeta;
		at: #SDLK_LHYPER put: #leftHyper;
		at: #SDLK_RHYPER put: #rightHyper;
		at: #SDLK_LSHIFT put: #leftShift;
		at: #SDLK_RSHIFT put: #rightShift;
		at: #SDLK_LCTRL put: #leftCtrl;
		at: #SDLK_RCTRL put: #rightCtrl;
		at: #SDLK_LALT put: #leftAlt;
		at: #SDLK_RALT put: #rightAlt;
		at: #SDLK_LGUI put: #leftGUI;
		at: #SDLK_RGUI put: #rightGUI.

	^ dict
]

{ #category : 'accessing enum' }
SDL3Keycode class >> equals [
	"This method was automatically generated"
	^ SDLK_EQUALS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> escape [
	"This method was automatically generated"
	^ SDLK_ESCAPE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> exclaim [
	"This method was automatically generated"
	^ SDLK_EXCLAIM
]

{ #category : 'accessing enum' }
SDL3Keycode class >> execute [
	"This method was automatically generated"
	^ SDLK_EXECUTE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> exsel [
	"This method was automatically generated"
	^ SDLK_EXSEL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f [
	"This method was automatically generated"
	^ SDLK_F
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f1 [
	"This method was automatically generated"
	^ SDLK_F1
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f10 [
	"This method was automatically generated"
	^ SDLK_F10
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f11 [
	"This method was automatically generated"
	^ SDLK_F11
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f12 [
	"This method was automatically generated"
	^ SDLK_F12
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f13 [
	"This method was automatically generated"
	^ SDLK_F13
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f14 [
	"This method was automatically generated"
	^ SDLK_F14
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f15 [
	"This method was automatically generated"
	^ SDLK_F15
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f16 [
	"This method was automatically generated"
	^ SDLK_F16
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f17 [
	"This method was automatically generated"
	^ SDLK_F17
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f18 [
	"This method was automatically generated"
	^ SDLK_F18
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f19 [
	"This method was automatically generated"
	^ SDLK_F19
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f2 [
	"This method was automatically generated"
	^ SDLK_F2
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f20 [
	"This method was automatically generated"
	^ SDLK_F20
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f21 [
	"This method was automatically generated"
	^ SDLK_F21
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f22 [
	"This method was automatically generated"
	^ SDLK_F22
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f23 [
	"This method was automatically generated"
	^ SDLK_F23
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f24 [
	"This method was automatically generated"
	^ SDLK_F24
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f3 [
	"This method was automatically generated"
	^ SDLK_F3
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f4 [
	"This method was automatically generated"
	^ SDLK_F4
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f5 [
	"This method was automatically generated"
	^ SDLK_F5
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f6 [
	"This method was automatically generated"
	^ SDLK_F6
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f7 [
	"This method was automatically generated"
	^ SDLK_F7
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f8 [
	"This method was automatically generated"
	^ SDLK_F8
]

{ #category : 'accessing enum' }
SDL3Keycode class >> f9 [
	"This method was automatically generated"
	^ SDLK_F9
]

{ #category : 'accessing enum' }
SDL3Keycode class >> find [
	"This method was automatically generated"
	^ SDLK_FIND
]

{ #category : 'accessing enum' }
SDL3Keycode class >> g [
	"This method was automatically generated"
	^ SDLK_G
]

{ #category : 'accessing enum' }
SDL3Keycode class >> grave [
	"This method was automatically generated"
	^ SDLK_GRAVE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> greater [
	"This method was automatically generated"
	^ SDLK_GREATER
]

{ #category : 'accessing enum' }
SDL3Keycode class >> h [
	"This method was automatically generated"
	^ SDLK_H
]

{ #category : 'accessing enum' }
SDL3Keycode class >> hashKey [
	"This method was automatically generated"
	^ SDLK_HASH
]

{ #category : 'accessing enum' }
SDL3Keycode class >> help [
	"This method was automatically generated"
	^ SDLK_HELP
]

{ #category : 'accessing enum' }
SDL3Keycode class >> home [
	"This method was automatically generated"
	^ SDLK_HOME
]

{ #category : 'accessing enum' }
SDL3Keycode class >> i [
	"This method was automatically generated"
	^ SDLK_I
]

{ #category : 'accessing enum' }
SDL3Keycode class >> insert [
	"This method was automatically generated"
	^ SDLK_INSERT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> j [
	"This method was automatically generated"
	^ SDLK_J
]

{ #category : 'accessing enum' }
SDL3Keycode class >> k [
	"This method was automatically generated"
	^ SDLK_K
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad0 [
	"This method was automatically generated"
	^ SDLK_KP_0
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad00 [
	"This method was automatically generated"
	^ SDLK_KP_00
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad000 [
	"This method was automatically generated"
	^ SDLK_KP_000
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad1 [
	"This method was automatically generated"
	^ SDLK_KP_1
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad2 [
	"This method was automatically generated"
	^ SDLK_KP_2
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad3 [
	"This method was automatically generated"
	^ SDLK_KP_3
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad4 [
	"This method was automatically generated"
	^ SDLK_KP_4
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad5 [
	"This method was automatically generated"
	^ SDLK_KP_5
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad6 [
	"This method was automatically generated"
	^ SDLK_KP_6
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad7 [
	"This method was automatically generated"
	^ SDLK_KP_7
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad8 [
	"This method was automatically generated"
	^ SDLK_KP_8
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypad9 [
	"This method was automatically generated"
	^ SDLK_KP_9
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadA [
	"This method was automatically generated"
	^ SDLK_KP_A
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadAmpersand [
	"This method was automatically generated"
	^ SDLK_KP_AMPERSAND
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadAt [
	"This method was automatically generated"
	^ SDLK_KP_AT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadB [
	"This method was automatically generated"
	^ SDLK_KP_B
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadBackspace [
	"This method was automatically generated"
	^ SDLK_KP_BACKSPACE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadBinary [
	"This method was automatically generated"
	^ SDLK_KP_BINARY
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadC [
	"This method was automatically generated"
	^ SDLK_KP_C
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadClear [
	"This method was automatically generated"
	^ SDLK_KP_CLEAR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadClearentry [
	"This method was automatically generated"
	^ SDLK_KP_CLEARENTRY
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadColon [
	"This method was automatically generated"
	^ SDLK_KP_COLON
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadComma [
	"This method was automatically generated"
	^ SDLK_KP_COMMA
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadD [
	"This method was automatically generated"
	^ SDLK_KP_D
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadDecimal [
	"This method was automatically generated"
	^ SDLK_KP_DECIMAL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadDivide [
	"This method was automatically generated"
	^ SDLK_KP_DIVIDE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadDoubleAmpersand [
	"This method was automatically generated"
	^ SDLK_KP_DBLAMPERSAND
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadDoubleVerticalbar [
	"This method was automatically generated"
	^ SDLK_KP_DBLVERTICALBAR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadE [
	"This method was automatically generated"
	^ SDLK_KP_E
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadEnter [
	"This method was automatically generated"
	^ SDLK_KP_ENTER
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadEquals [
	"This method was automatically generated"
	^ SDLK_KP_EQUALS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadEqualsas400 [
	"This method was automatically generated"
	^ SDLK_KP_EQUALSAS400
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadExclam [
	"This method was automatically generated"
	^ SDLK_KP_EXCLAM
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadF [
	"This method was automatically generated"
	^ SDLK_KP_F
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadGreater [
	"This method was automatically generated"
	^ SDLK_KP_GREATER
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadHash [
	"This method was automatically generated"
	^ SDLK_KP_HASH
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadHexadecimal [
	"This method was automatically generated"
	^ SDLK_KP_HEXADECIMAL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadLeftBrace [
	"This method was automatically generated"
	^ SDLK_KP_LEFTBRACE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadLeftParenthesis [
	"This method was automatically generated"
	^ SDLK_KP_LEFTPAREN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadLess [
	"This method was automatically generated"
	^ SDLK_KP_LESS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMemadd [
	"This method was automatically generated"
	^ SDLK_KP_MEMADD
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMemclear [
	"This method was automatically generated"
	^ SDLK_KP_MEMCLEAR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMemdivide [
	"This method was automatically generated"
	^ SDLK_KP_MEMDIVIDE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMemmultiply [
	"This method was automatically generated"
	^ SDLK_KP_MEMMULTIPLY
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMemrecall [
	"This method was automatically generated"
	^ SDLK_KP_MEMRECALL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMemstore [
	"This method was automatically generated"
	^ SDLK_KP_MEMSTORE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMemsubtract [
	"This method was automatically generated"
	^ SDLK_KP_MEMSUBTRACT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMinus [
	"This method was automatically generated"
	^ SDLK_KP_MINUS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadMultiply [
	"This method was automatically generated"
	^ SDLK_KP_MULTIPLY
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadOctal [
	"This method was automatically generated"
	^ SDLK_KP_OCTAL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadPercent [
	"This method was automatically generated"
	^ SDLK_KP_PERCENT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadPeriod [
	"This method was automatically generated"
	^ SDLK_KP_PERIOD
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadPlus [
	"This method was automatically generated"
	^ SDLK_KP_PLUS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadPlusMinus [
	"This method was automatically generated"
	^ SDLK_KP_PLUSMINUS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadPower [
	"This method was automatically generated"
	^ SDLK_KP_POWER
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadRightBrace [
	"This method was automatically generated"
	^ SDLK_KP_RIGHTBRACE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadRightParenthesis [
	"This method was automatically generated"
	^ SDLK_KP_RIGHTPAREN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadSpace [
	"This method was automatically generated"
	^ SDLK_KP_SPACE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadTab [
	"This method was automatically generated"
	^ SDLK_KP_TAB
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadVerticalbar [
	"This method was automatically generated"
	^ SDLK_KP_VERTICALBAR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> keypadXor [
	"This method was automatically generated"
	^ SDLK_KP_XOR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> l [
	"This method was automatically generated"
	^ SDLK_L
]

{ #category : 'accessing enum' }
SDL3Keycode class >> left [
	"This method was automatically generated"
	^ SDLK_LEFT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftAlt [
	"This method was automatically generated"
	^ SDLK_LALT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftBrace [
	"This method was automatically generated"
	^ SDLK_LEFTBRACE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftBracket [
	"This method was automatically generated"
	^ SDLK_LEFTBRACKET
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftCtrl [
	"This method was automatically generated"
	^ SDLK_LCTRL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftGUI [
	"This method was automatically generated"
	^ SDLK_LGUI
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftHyper [
	"This method was automatically generated"
	^ SDLK_LHYPER
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftMeta [
	"This method was automatically generated"
	^ SDLK_LMETA
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftParenthesis [
	"This method was automatically generated"
	^ SDLK_LEFTPAREN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftShift [
	"This method was automatically generated"
	^ SDLK_LSHIFT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> leftTab [
	"This method was automatically generated"
	^ SDLK_LEFT_TAB
]

{ #category : 'accessing enum' }
SDL3Keycode class >> less [
	"This method was automatically generated"
	^ SDLK_LESS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> level5Shift [
	"This method was automatically generated"
	^ SDLK_LEVEL5_SHIFT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> m [
	"This method was automatically generated"
	^ SDLK_M
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaEject [
	"This method was automatically generated"
	^ SDLK_MEDIA_EJECT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaFastForward [
	"This method was automatically generated"
	^ SDLK_MEDIA_FAST_FORWARD
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaNextTrack [
	"This method was automatically generated"
	^ SDLK_MEDIA_NEXT_TRACK
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaPause [
	"This method was automatically generated"
	^ SDLK_MEDIA_PAUSE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaPlay [
	"This method was automatically generated"
	^ SDLK_MEDIA_PLAY
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaPlayPause [
	"This method was automatically generated"
	^ SDLK_MEDIA_PLAY_PAUSE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaPreviousTrack [
	"This method was automatically generated"
	^ SDLK_MEDIA_PREVIOUS_TRACK
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaRecord [
	"This method was automatically generated"
	^ SDLK_MEDIA_RECORD
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaRewind [
	"This method was automatically generated"
	^ SDLK_MEDIA_REWIND
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaSelect [
	"This method was automatically generated"
	^ SDLK_MEDIA_SELECT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mediaStop [
	"This method was automatically generated"
	^ SDLK_MEDIA_STOP
]

{ #category : 'accessing enum' }
SDL3Keycode class >> menu [
	"This method was automatically generated"
	^ SDLK_MENU
]

{ #category : 'accessing enum' }
SDL3Keycode class >> minus [
	"This method was automatically generated"
	^ SDLK_MINUS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mode [
	"This method was automatically generated"
	^ SDLK_MODE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> multiKeyCompose [
	"This method was automatically generated"
	^ SDLK_MULTI_KEY_COMPOSE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> mute [
	"This method was automatically generated"
	^ SDLK_MUTE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> n [
	"This method was automatically generated"
	^ SDLK_N
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number0 [
	"This method was automatically generated"
	^ SDLK_0
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number1 [
	"This method was automatically generated"
	^ SDLK_1
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number2 [
	"This method was automatically generated"
	^ SDLK_2
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number3 [
	"This method was automatically generated"
	^ SDLK_3
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number4 [
	"This method was automatically generated"
	^ SDLK_4
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number5 [
	"This method was automatically generated"
	^ SDLK_5
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number6 [
	"This method was automatically generated"
	^ SDLK_6
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number7 [
	"This method was automatically generated"
	^ SDLK_7
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number8 [
	"This method was automatically generated"
	^ SDLK_8
]

{ #category : 'accessing enum' }
SDL3Keycode class >> number9 [
	"This method was automatically generated"
	^ SDLK_9
]

{ #category : 'accessing enum' }
SDL3Keycode class >> numlockclear [
	"This method was automatically generated"
	^ SDLK_NUMLOCKCLEAR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> o [
	"This method was automatically generated"
	^ SDLK_O
]

{ #category : 'accessing enum' }
SDL3Keycode class >> oper [
	"This method was automatically generated"
	^ SDLK_OPER
]

{ #category : 'accessing enum' }
SDL3Keycode class >> out [
	"This method was automatically generated"
	^ SDLK_OUT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> p [
	"This method was automatically generated"
	^ SDLK_P
]

{ #category : 'accessing enum' }
SDL3Keycode class >> pageDown [
	"This method was automatically generated"
	^ SDLK_PAGEDOWN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> pageUp [
	"This method was automatically generated"
	^ SDLK_PAGEUP
]

{ #category : 'accessing enum' }
SDL3Keycode class >> paste [
	"This method was automatically generated"
	^ SDLK_PASTE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> pause [
	"This method was automatically generated"
	^ SDLK_PAUSE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> percent [
	"This method was automatically generated"
	^ SDLK_PERCENT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> period [
	"This method was automatically generated"
	^ SDLK_PERIOD
]

{ #category : 'accessing enum' }
SDL3Keycode class >> pipe [
	"This method was automatically generated"
	^ SDLK_PIPE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> plus [
	"This method was automatically generated"
	^ SDLK_PLUS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> plusMinus [
	"This method was automatically generated"
	^ SDLK_PLUSMINUS
]

{ #category : 'accessing enum' }
SDL3Keycode class >> power [
	"This method was automatically generated"
	^ SDLK_POWER
]

{ #category : 'accessing enum' }
SDL3Keycode class >> printscreen [
	"This method was automatically generated"
	^ SDLK_PRINTSCREEN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> prior [
	"This method was automatically generated"
	^ SDLK_PRIOR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> q [
	"This method was automatically generated"
	^ SDLK_Q
]

{ #category : 'accessing enum' }
SDL3Keycode class >> question [
	"This method was automatically generated"
	^ SDLK_QUESTION
]

{ #category : 'accessing enum' }
SDL3Keycode class >> r [
	"This method was automatically generated"
	^ SDLK_R
]

{ #category : 'accessing enum' }
SDL3Keycode class >> return [
	"This method was automatically generated"
	^ SDLK_RETURN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> return2 [
	"This method was automatically generated"
	^ SDLK_RETURN2
]

{ #category : 'accessing enum' }
SDL3Keycode class >> right [
	"This method was automatically generated"
	^ SDLK_RIGHT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightAlt [
	"This method was automatically generated"
	^ SDLK_RALT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightBrace [
	"This method was automatically generated"
	^ SDLK_RIGHTBRACE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightBracket [
	"This method was automatically generated"
	^ SDLK_RIGHTBRACKET
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightCtrl [
	"This method was automatically generated"
	^ SDLK_RCTRL
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightGUI [
	"This method was automatically generated"
	^ SDLK_RGUI
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightHyper [
	"This method was automatically generated"
	^ SDLK_RHYPER
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightMeta [
	"This method was automatically generated"
	^ SDLK_RMETA
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightParenthesis [
	"This method was automatically generated"
	^ SDLK_RIGHTPAREN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> rightShift [
	"This method was automatically generated"
	^ SDLK_RSHIFT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> s [
	"This method was automatically generated"
	^ SDLK_S
]

{ #category : 'accessing enum' }
SDL3Keycode class >> scrollLock [
	"This method was automatically generated"
	^ SDLK_SCROLLLOCK
]

{ #category : 'accessing enum' }
SDL3Keycode class >> select [
	"This method was automatically generated"
	^ SDLK_SELECT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> semiColon [
	"This method was automatically generated"
	^ SDLK_SEMICOLON
]

{ #category : 'accessing enum' }
SDL3Keycode class >> separator [
	"This method was automatically generated"
	^ SDLK_SEPARATOR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> slash [
	"This method was automatically generated"
	^ SDLK_SLASH
]

{ #category : 'accessing enum' }
SDL3Keycode class >> sleep [
	"This method was automatically generated"
	^ SDLK_SLEEP
]

{ #category : 'accessing enum' }
SDL3Keycode class >> softLeft [
	"This method was automatically generated"
	^ SDLK_SOFTLEFT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> softRight [
	"This method was automatically generated"
	^ SDLK_SOFTRIGHT
]

{ #category : 'accessing enum' }
SDL3Keycode class >> space [
	"This method was automatically generated"
	^ SDLK_SPACE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> stop [
	"This method was automatically generated"
	^ SDLK_STOP
]

{ #category : 'accessing enum' }
SDL3Keycode class >> sysreq [
	"This method was automatically generated"
	^ SDLK_SYSREQ
]

{ #category : 'accessing enum' }
SDL3Keycode class >> t [
	"This method was automatically generated"
	^ SDLK_T
]

{ #category : 'accessing enum' }
SDL3Keycode class >> tab [
	"This method was automatically generated"
	^ SDLK_TAB
]

{ #category : 'accessing enum' }
SDL3Keycode class >> thousandsSeparator [
	"This method was automatically generated"
	^ SDLK_THOUSANDSSEPARATOR
]

{ #category : 'accessing enum' }
SDL3Keycode class >> tilde [
	"This method was automatically generated"
	^ SDLK_TILDE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> u [
	"This method was automatically generated"
	^ SDLK_U
]

{ #category : 'accessing enum' }
SDL3Keycode class >> underscore [
	"This method was automatically generated"
	^ SDLK_UNDERSCORE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> undo [
	"This method was automatically generated"
	^ SDLK_UNDO
]

{ #category : 'accessing enum' }
SDL3Keycode class >> unknown [
	"This method was automatically generated"
	^ SDLK_UNKNOWN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> up [
	"This method was automatically generated"
	^ SDLK_UP
]

{ #category : 'accessing enum' }
SDL3Keycode class >> v [
	"This method was automatically generated"
	^ SDLK_V
]

{ #category : 'accessing enum' }
SDL3Keycode class >> volumeDown [
	"This method was automatically generated"
	^ SDLK_VOLUMEDOWN
]

{ #category : 'accessing enum' }
SDL3Keycode class >> volumeUp [
	"This method was automatically generated"
	^ SDLK_VOLUMEUP
]

{ #category : 'accessing enum' }
SDL3Keycode class >> w [
	"This method was automatically generated"
	^ SDLK_W
]

{ #category : 'accessing enum' }
SDL3Keycode class >> wake [
	"This method was automatically generated"
	^ SDLK_WAKE
]

{ #category : 'accessing enum' }
SDL3Keycode class >> x [
	"This method was automatically generated"
	^ SDLK_X
]

{ #category : 'accessing enum' }
SDL3Keycode class >> y [
	"This method was automatically generated"
	^ SDLK_Y
]

{ #category : 'accessing enum' }
SDL3Keycode class >> z [
	"This method was automatically generated"
	^ SDLK_Z
]
